//// Client package generation.
////
//// Assembles the standalone Gleam project that compiles to the browser
//// SPA: gleam.toml, app.gleam (Lustre entry point with per-page TEA loop),
//// transport.gleam (WebSocket FFI bridge), and router.gleam (client-side
//// route parsing). The generated package lives in .generated_clients/<namespace>.

import glance
import gleam/dict
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/result
import gleam/set
import gleam/string
import libero/field_type.{UserType}
import rally/internal/generator
import rally/internal/types.{
  type ClientContextContract, type PageContract, type ScanConfig,
  type ScannedRoute, ClientContextContract,
}
import tom

pub type GeneratedFile {
  GeneratedFile(path: String, content: String)
}

pub fn generate_package(
  routes routes: List(ScannedRoute),
  contracts contracts: List(#(ScannedRoute, PageContract)),
  config config: ScanConfig,
  transport_ffi_content transport_ffi_content: String,
  has_client_context has_client_context: Bool,
) -> List(GeneratedFile) {
  generate_package_with_client_context_contract(
    routes:,
    contracts:,
    config:,
    transport_ffi_content:,
    client_context_contract: case has_client_context {
      True -> Some(empty_client_context_contract())
      False -> None
    },
    client_context_module: "client_context",
    protocol: config.protocol,
  )
}

pub fn generate_package_with_client_context_contract(
  routes routes: List(ScannedRoute),
  contracts contracts: List(#(ScannedRoute, PageContract)),
  config config: ScanConfig,
  transport_ffi_content transport_ffi_content: String,
  client_context_contract client_context_contract: Option(ClientContextContract),
  client_context_module client_context_module: String,
  protocol protocol: String,
) -> List(GeneratedFile) {
  [
    GeneratedFile(
      config.client_root <> "/src/generated/transport_ffi.mjs",
      transport_ffi_content,
    ),
    GeneratedFile(
      config.client_root <> "/src/generated/transport.gleam",
      transport_gleam(protocol),
    ),
    GeneratedFile(
      config.client_root <> "/src/generated/router_ffi.mjs",
      router_ffi_mjs(),
    ),
    GeneratedFile(
      config.client_root <> "/src/generated/router.gleam",
      client_router(routes),
    ),
    GeneratedFile(
      config.client_root <> "/src/generated/app.gleam",
      app_gleam(
        routes:,
        contracts:,
        client_context_contract:,
        client_context_module:,
      ),
    ),
    GeneratedFile(
      config.client_root <> "/src/generated/config.mjs",
      config_mjs(protocol),
    ),
  ]
}

fn config_mjs(protocol: String) -> String {
  "// Generated by Rally — do not edit.\n"
  <> "export const protocol = \""
  <> protocol
  <> "\";\n"
}

fn empty_client_context_contract() -> ClientContextContract {
  ClientContextContract(
    context_variants: [],
    msg_variants: [],
    has_init: True,
    has_update: True,
  )
}

fn import_as(module_path: String, alias: String) -> String {
  case last_segment(module_path) == alias {
    True -> "import " <> module_path
    False -> "import " <> module_path <> " as " <> alias
  }
}

fn client_router(routes: List(ScannedRoute)) -> String {
  let server_router = generator.generate(routes)
  let client_fns =
    "

/// Read the browser's current location.
@external(javascript, \"./router_ffi.mjs\", \"currentUrl\")
fn current_url() -> String

/// Parse the current browser URL into a Route.
pub fn parse_route_from_url() -> Route {
  let url = current_url()
  let uri = case uri.parse(url) {
    Ok(u) -> u
    Error(_) -> {
      let assert Ok(fallback) = uri.parse(\"http://localhost/\")
      fallback
    }
  }
  parse_route(uri)
}
"
  server_router <> "\n" <> client_fns
}

pub fn generate_gleam_toml(
  all_client_files all_client_files: List(GeneratedFile),
  server_deps server_deps: dict.Dict(String, tom.Toml),
  client_root client_root: String,
  protocol protocol: String,
) -> GeneratedFile {
  let header =
    "name = \"client\"\nversion = \"0.1.0\"\ntarget = \"javascript\"\n\n[dependencies]\ngleam_stdlib = \">= 0.60.0 and < 2.0.0\"\nlustre = \">= 5.7.0 and < 7.0.0\"\nmodem = \">= 2.0.0 and < 3.0.0\"\n"

  let depth = list.length(string.split(client_root, "/"))
  let prefix = string.repeat("../", depth)

  let json_deps = case protocol {
    "json" ->
      "gleam_json = \">= 3.1.0 and < 4.0.0\"\nlibero = \">= 6.0.0 and < 7.0.0\"\n"
    _ -> ""
  }

  let client_imports = collect_client_imports(all_client_files)
  let baseline =
    set.from_list([
      "gleam_stdlib", "lustre", "modem", "rally", "marmot", "gleeunit",
    ])
  let json_baseline = case protocol {
    "json" -> set.from_list(["libero", "gleam_json"])
    _ -> set.new()
  }
  let exclude = set.union(baseline, json_baseline)

  let extra_deps =
    server_deps
    |> dict.to_list
    |> list.filter(fn(pair) {
      !set.contains(exclude, pair.0)
      && !is_browser_impossible(pair.0)
      && package_needed(pair.0, client_imports)
    })
    |> list.sort(fn(a, b) { string.compare(a.0, b.0) })
    |> list.map(fn(pair) {
      format_dep(name: pair.0, value: pair.1, prefix: prefix)
    })
    |> string.join("")

  GeneratedFile(client_root <> "/gleam.toml", header <> json_deps <> extra_deps)
}

fn collect_client_imports(files: List(GeneratedFile)) -> set.Set(String) {
  files
  |> list.filter(fn(f) { string.ends_with(f.path, ".gleam") })
  |> list.flat_map(fn(f) {
    case glance.module(f.content) {
      Ok(ast) -> list.map(ast.imports, fn(def) { def.definition.module })
      _ -> []
    }
  })
  |> set.from_list
}

fn package_needed(
  package_name: String,
  client_imports: set.Set(String),
) -> Bool {
  let prefix = string.replace(package_name, "_", "/")
  set.to_list(client_imports)
  |> list.any(fn(import_path) {
    import_path == prefix || string.starts_with(import_path, prefix <> "/")
  })
}

fn is_browser_impossible(name: String) -> Bool {
  list.contains(["mist", "sqlight", "simplifile", "gleam_erlang"], name)
}

fn format_dep(
  name name: String,
  value value: tom.Toml,
  prefix prefix: String,
) -> String {
  case value {
    tom.String(version) -> name <> " = \"" <> version <> "\"\n"
    tom.InlineTable(table) | tom.Table(table) -> {
      case dict.get(table, "path") {
        Ok(tom.String(path)) ->
          name <> " = { path = \"" <> client_path(path, prefix) <> "\" }\n"
        _ -> {
          let entries =
            dict.to_list(table)
            |> list.map(fn(pair) {
              case pair.1 {
                tom.String(s) -> pair.0 <> " = \"" <> s <> "\""
                _ -> pair.0 <> " = \"???\""
              }
            })
            |> string.join(", ")
          name <> " = { " <> entries <> " }\n"
        }
      }
    }
    _ -> ""
  }
}

fn client_path(path: String, prefix: String) -> String {
  case string.starts_with(path, "/") {
    True -> path
    _ -> prefix <> path
  }
}

fn transport_gleam(_protocol: String) -> String {
  let protocol_wire = "\"./protocol_wire.mjs\""
  let transport_ffi = "\"./transport_ffi.mjs\""

  "// Generated by Rally — do not edit.
import gleam/dynamic.{type Dynamic}

pub type DecodeError {
  DecodeError(message: String)
}

/// Initialize the WebSocket connection. Call once on app startup.
@external(javascript, " <> transport_ffi <> ", \"ensureSocket\")
pub fn init(url: String) -> Nil

/// Send a message to the server. The protocol_wire facade encodes
/// the message according to the configured protocol (ETF binary or JSON).
@external(javascript, " <> transport_ffi <> ", \"send\")
fn send_raw(
  url: String,
  page: String,
  msg: a,
  callback: fn(b) -> Nil,
) -> Nil

/// Register a handler for push messages from the server.
/// The handler is called with the decoded push value whenever
/// the server sends a ToClient for this page.
@external(javascript, " <> transport_ffi <> ", \"registerPushHandler\")
pub fn register_push_handler(
  page: String,
  handler: fn(Dynamic) -> Nil,
) -> Nil

/// Register a callback that fires when the WebSocket connects
/// (both initial connect and reconnects).
@external(javascript, " <> transport_ffi <> ", \"registerOnConnect\")
pub fn register_on_connect(callback: fn() -> Nil) -> Nil

/// Register a callback that fires when the WebSocket disconnects.
@external(javascript, " <> transport_ffi <> ", \"registerOnDisconnect\")
pub fn register_on_disconnect(callback: fn(String) -> Nil) -> Nil

/// Register a handler that fires when an RPC fails at the framework
/// layer (dispatch errors, malformed requests, decode failures, or
/// connection loss while a call is in flight). Domain-level errors
/// returned by handlers flow through the per-call callback as usual.
@external(javascript, " <> transport_ffi <> ", \"registerRpcErrorHandler\")
pub fn register_rpc_error_handler(callback: fn(String) -> Nil) -> Nil

/// Send a ToServer message to the server.
/// Encodes the message and sends it over the WebSocket.
pub fn send_to_server(page: String, msg: a) -> Nil {
  send_raw(\"/ws\", page, msg, fn(_) { Nil })
}

/// Send an RPC call and invoke callback with the handler's return value.
/// Framework-level errors do not invoke this callback; they flow through
/// register_rpc_error_handler. User Msg types only need to handle whatever
/// shape the handler returns.
pub fn send_rpc(msg: a, callback: fn(b) -> Nil) -> Nil {
  send_raw(\"/ws\", \"rpc\", msg, callback)
}

/// Send route params to initialize the server-side page model.
/// Uses request_id 0 as the init sentinel.
pub fn send_page_init(page: String, params: a) -> Nil {
  send_page_init_raw(\"/ws\", page, params)
}

@external(javascript, " <> transport_ffi <> ", \"send_page_init\")
fn send_page_init_raw(url: String, page: String, params: a) -> Nil

/// Read SSR flags embedded in the page by the server.
/// Returns empty string if not present.
@external(javascript, " <> transport_ffi <> ", \"read_flags\")
pub fn read_flags() -> String

/// Read the server-provided ClientContext from SSR flags.
/// Returns empty string if not present.
@external(javascript, " <> transport_ffi <> ", \"read_client_context\")
pub fn read_client_context() -> String

/// Type-level identity cast. The JS runtime representation is unchanged;
/// this lets generated code bridge between Dynamic/generic and concrete types
/// where the value is already the correct shape (decoded ETF, SSR flags).
@external(javascript, " <> protocol_wire <> ", \"identity\")
pub fn coerce(value: a) -> b
"
}

type ClientContextSyncFields {
  ClientContextSyncFields(
    has_current_path: Bool,
    has_dark_mode: Bool,
    has_lang: Bool,
  )
}

fn client_context_sync_fields(
  contract: Option(ClientContextContract),
) -> ClientContextSyncFields {
  let fields = case contract {
    Some(contract) ->
      contract.context_variants
      |> list.find_map(fn(variant) {
        case variant.name {
          "ClientContext" -> Ok(variant.fields)
          _ -> Error(Nil)
        }
      })
      |> result.unwrap([])
      |> list.map(fn(field) { field.label })
      |> set.from_list
    None -> set.new()
  }

  ClientContextSyncFields(
    has_current_path: set.contains(fields, "current_path"),
    has_dark_mode: set.contains(fields, "dark_mode"),
    has_lang: set.contains(fields, "lang"),
  )
}

fn client_context_init_overlay(fields: ClientContextSyncFields) -> String {
  let assignments = []
  let assignments = case fields.has_current_path {
    True -> ["current_path: current_path", ..assignments]
    False -> assignments
  }
  let assignments = case fields.has_dark_mode {
    True -> ["dark_mode: rally_effect.read_dark_mode()", ..assignments]
    False -> assignments
  }
  let assignments = case fields.has_lang {
    True -> ["lang: rally_effect.read_lang()", ..assignments]
    False -> assignments
  }
  let assignments = list.reverse(assignments)

  case assignments {
    [] -> ""
    _ -> "  let client_context = client_context.ClientContext(
    ..client_context,
    " <> string.join(
        assignments,
        ",
    ",
      ) <> ",
  )
"
  }
}

fn app_gleam(
  routes routes: List(ScannedRoute),
  contracts contracts: List(#(ScannedRoute, PageContract)),
  client_context_contract client_context_contract: Option(ClientContextContract),
  client_context_module client_context_module: String,
) -> String {
  let has_client_context = option.is_some(client_context_contract)
  let sync_fields = client_context_sync_fields(client_context_contract)
  let init_context_overlay = client_context_init_overlay(sync_fields)
  let needs_rally_effect = sync_fields.has_dark_mode || sync_fields.has_lang

  // Build a lookup from variant_name -> PageContract for quick access
  let contract_map =
    contracts
    |> list.map(fn(pair) { #({ pair.0 }.variant_name, pair.1) })
    |> dict.from_list

  let push_registrations = generate_push_registrations(contracts)
  let page_model_type = generate_page_model_type(routes, contract_map)
  let page_msg_type = generate_page_msg_type(routes, contract_map)
  let init_page_fn =
    generate_init_page(routes:, contract_map:, has_client_context:)
  let hydrate_page_fn =
    generate_hydrate_page(routes:, contract_map:, has_client_context:)
  let reinit_server_fn = generate_reinit_server(routes, contract_map)
  let update_page_fn =
    generate_update_page(routes:, contract_map:, has_client_context:)
  let render_page_fn =
    generate_render_page(routes:, contract_map:, has_client_context:)

  // Collect all layout modules from routes
  let layout_modules =
    routes
    |> list.filter_map(fn(route) {
      case route.layout_module {
        Some(layout) -> Ok(layout)
        _ -> Error(Nil)
      }
    })
    |> list.unique

  let ctx_import = case has_client_context {
    True -> "\n" <> import_as(client_context_module, "client_context")
    False -> ""
  }

  let rally_effect_import = case needs_rally_effect {
    True -> "import rally/runtime/effect as rally_effect\n\n"
    False -> "\n"
  }

  let layout_imports = case layout_modules {
    [] -> ""
    mods ->
      list.map(mods, fn(mod) {
        "\nimport " <> mod <> " as " <> module_alias(mod)
      })
      |> string.join("")
  }

  let ctx_field = case has_client_context {
    True ->
      "\n    client_context: client_context.ClientContext,\n    current_path: String,"
    False -> ""
  }

  let ctx_msg_variant = case has_client_context {
    True -> "\n  ClientContextUpdate(client_context.ClientContextMsg)"
    False -> ""
  }

  let modem_init = "modem.init(fn(uri) { UrlChanged(router.parse_route(uri)) })"

  let ctx_decoder_name =
    "decode_"
    <> string.replace(client_context_module, "/", "_")
    <> "_client_context"

  let ctx_init = case has_client_context {
    True -> "  let flags = transport.read_flags()
  let #(ctx_model, ctx_effects) = client_context.init()
  let current_path = router.route_to_path(route)
  let client_context = case codec.decode_flags_typed(transport.read_client_context(), \"" <> ctx_decoder_name <> "\") {
    Ok(ctx) -> ctx
    Error(_) -> ctx_model
  }
" <> init_context_overlay <> "  let #(page_model, page_effects) = case flags {
    \"\" -> init_page(route: route, client_context: client_context)
    _ -> hydrate_page(route, flags, client_context)
  }
  #(Model(route:, page_model:, connection: Disconnected, client_context:, current_path:),
    effect.batch([init_transport(), " <> modem_init <> ", effect.map(ctx_effects, ClientContextUpdate), page_effects]))"
    False -> "  let flags = transport.read_flags()
  let #(page_model, page_effects) = case flags {
    \"\" -> init_page(route: route)
    _ -> hydrate_page(route, flags)
  }
  #(Model(route:, page_model:, connection: Disconnected),
    effect.batch([init_transport(), " <> modem_init <> ", page_effects]))"
  }

  let ctx_update_arm = case has_client_context {
    True ->
      "
    ClientContextUpdate(client_context_msg) -> {
      let #(new_client_context, client_context_effects) = client_context.update(model.client_context, client_context_msg)
      #(Model(..model, client_context: new_client_context), effect.map(client_context_effects, ClientContextUpdate))
    }"
    False -> ""
  }

  let url_changed_body = case has_client_context {
    True ->
      case sync_fields.has_current_path {
        True ->
          "      case route == model.route {
        True -> #(model, effect.none())
        False -> {
          let current_path = router.route_to_path(route)
          let new_client_context =
            client_context.ClientContext(..model.client_context, current_path:)
          let #(page_model, page_effects) = init_page(route: route, client_context: new_client_context)
          #(Model(..model, route:, page_model:, client_context: new_client_context, current_path:), page_effects)
        }
      }"
        False ->
          "      case route == model.route {
        True -> #(model, effect.none())
        False -> {
          let current_path = router.route_to_path(route)
          let #(page_model, page_effects) = init_page(route: route, client_context: model.client_context)
          #(Model(..model, route:, page_model:, current_path:), page_effects)
        }
      }"
      }
    False ->
      "      case route == model.route {
        True -> #(model, effect.none())
        False -> {
          let #(page_model, page_effects) = init_page(route)
          #(Model(..model, route:, page_model:), page_effects)
        }
      }"
  }

  let page_msg_body = case has_client_context {
    True ->
      "      let #(page_model, page_effects, ctx_msg) = update_page(page_model: model.page_model, page_msg: page_msg, client_context: model.client_context)
      let #(new_client_context, ctx_effects) = case ctx_msg {
        Some(cm) -> {
          let #(cc, ce) = client_context.update(model.client_context, cm)
          #(cc, effect.map(ce, ClientContextUpdate))
        }
        None -> #(model.client_context, effect.none())
      }
      #(Model(..model, page_model:, client_context: new_client_context), effect.batch([page_effects, ctx_effects]))"
    False ->
      "      let #(page_model, page_effects) = update_page(page_model: model.page_model, page_msg: page_msg)
      #(Model(..model, page_model:), page_effects)"
  }

  let ctx_push_registration = case has_client_context {
    True ->
      "\n    let _ = transport.register_push_handler(\"__ClientContext__\", fn(raw) {\n      dispatch(ClientContextUpdate(transport.coerce(raw)))\n    })"
    False -> ""
  }

  let render_page_call = case has_client_context {
    True -> "render_page(model.page_model, model.client_context)"
    False -> "render_page(model.page_model)"
  }

  let layout_arms = case layout_modules {
    [] -> ""
    _ ->
      list.map(routes, fn(route) {
        case route.layout_module {
          Some(layout) -> {
            let variant = route.variant_name <> "PageModel"
            let alias = module_alias(layout)
            case has_client_context {
              True ->
                "    "
                <> variant
                <> "(_) ->\n      "
                <> alias
                <> ".layout(model.client_context, ClientContextUpdate, content)\n"
              False ->
                "    "
                <> variant
                <> "(_) ->\n      "
                <> alias
                <> ".layout(content)\n"
            }
          }
          None -> ""
        }
      })
      |> string.join("")
      |> fn(arms) {
        case arms {
          "" -> ""
          _ -> arms <> "    _ -> content\n"
        }
      }
  }

  let wrap_layout = case layout_arms {
    "" -> ""
    arms ->
      "\nfn wrap_layout(model: Model, content: Element(Msg)) -> Element(Msg) {\n  case model.page_model {\n"
      <> arms
      <> "  }\n}\n"
  }

  let view_body = case layout_arms {
    "" -> "  html.div([attr.class(\"rally-app\")], [
    " <> render_page_call <> ",
    connection_banner(model.connection),
  ])"
    _ -> "  let content =
    html.div([attr.class(\"rally-app\")], [
      " <> render_page_call <> ",
      connection_banner(model.connection),
    ])
  wrap_layout(model, content)"
  }

  let page_imports = generate_page_imports(routes, contract_map)

  let option_import = case has_client_context {
    True -> "import gleam/option.{type Option, None, Some}\n"
    False -> ""
  }
  "// Generated by Rally — do not edit.
" <> option_import <> "import lustre
import lustre/attribute as attr
import lustre/element.{type Element}
import lustre/element/html
import lustre/effect.{type Effect}
import modem
import generated/codec
import generated/router
import generated/transport
" <> rally_effect_import <> "@external(javascript, \"../generated/codec_ffi.mjs\", \"ensure_decoders\")
fn ensure_decoders() -> Nil
" <> page_imports <> ctx_import <> layout_imports <> "

" <> page_model_type <> "

" <> page_msg_type <> "

pub type Model {
  Model(
    route: router.Route,
    page_model: PageModel,
    connection: Connection," <> ctx_field <> "
  )
}

pub type Connection {
  Connected
  Disconnected
  Reconnecting
}

pub type Msg {
  UrlChanged(router.Route)
  PageMsg(PageMsg)
  TransportConnected
  TransportDisconnected(reason: String)" <> ctx_msg_variant <> "
}

pub fn main() {
  let app = lustre.application(init, update, view)
  lustre.start(app, \"#app\", Nil)
}

fn init(_flags: Nil) -> #(Model, Effect(Msg)) {
  let _ = ensure_decoders()
  let route = router.parse_route_from_url()
" <> ctx_init <> "
}

fn init_transport() -> Effect(Msg) {
  effect.from(fn(dispatch) {
    let _ = transport.init(\"/ws\")
    let _ = transport.register_on_connect(fn() { dispatch(TransportConnected) })
    let _ = transport.register_on_disconnect(fn(reason) { dispatch(TransportDisconnected(reason)) })
" <> push_registrations <> ctx_push_registration <> "
    Nil
  })
}

" <> init_page_fn <> "

" <> hydrate_page_fn <> "

" <> reinit_server_fn <> "

" <> update_page_fn <> "

" <> render_page_fn <> "

fn update(model: Model, msg: Msg) -> #(Model, Effect(Msg)) {
  case msg {
    UrlChanged(route) -> {
" <> url_changed_body <> "
    }
    PageMsg(page_msg) -> {
" <> page_msg_body <> "
    }
    TransportConnected ->
      #(Model(..model, connection: Connected), reinit_server(model.route))
    TransportDisconnected(_reason) ->
      #(Model(..model, connection: Disconnected), effect.none())" <> ctx_update_arm <> "
  }
}

" <> wrap_layout <> "
fn view(model: Model) -> Element(Msg) {
" <> view_body <> "
}

fn connection_banner(connection: Connection) -> Element(Msg) {
  case connection {
    Connected -> html.text(\"\")
    Disconnected ->
      html.div(
        [attr.class(\"rally-banner rally-banner--disconnected\")],
        [html.text(\"Disconnected from server. Reconnecting...\")],
      )
    Reconnecting ->
      html.div(
        [attr.class(\"rally-banner rally-banner--reconnecting\")],
        [html.text(\"Reconnecting...\")],
      )
  }
}
"
}

fn generate_push_registrations(
  contracts: List(#(ScannedRoute, PageContract)),
) -> String {
  contracts
  |> list.filter_map(fn(pair) {
    let #(route, contract) = pair
    case find_to_client_msg_wrapper(route, contract) {
      Ok(wrapper) -> {
        let alias = page_module_alias(route)
        Ok("
    let _ =
      transport.register_push_handler(\"" <> route.variant_name <> "\", fn(raw) {
        dispatch(PageMsg(" <> route.variant_name <> "PageMsg(" <> alias <> "." <> wrapper <> "(transport.coerce(raw)))))
      })")
      }
      Error(_) -> Error(Nil)
    }
  })
  |> string.join("")
}

fn find_to_client_msg_wrapper(
  route: ScannedRoute,
  contract: PageContract,
) -> Result(String, Nil) {
  contract.msg_variants
  |> list.find_map(fn(variant) {
    case variant.fields {
      [field] ->
        case field.type_ {
          UserType(module_path:, type_name: "ToClient", args: [])
            if module_path == route.module_path
          -> Ok(variant.name)
          _ -> Error(Nil)
        }
      _ -> Error(Nil)
    }
  })
}

fn router_ffi_mjs() -> String {
  "// Generated by Rally — do not edit.
//
// Browser router FFI — reads the current URL.
// Used by the generated client router.gleam.

export function currentUrl() {
  return globalThis.location?.href ?? \"http://localhost/\";
}
"
}

fn generate_page_model_type(
  routes: List(ScannedRoute),
  contract_map: dict.Dict(String, PageContract),
) -> String {
  let variants =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          Ok("  " <> route.variant_name <> "PageModel(" <> alias <> ".Model)")
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")
  "pub type PageModel {\n" <> variants <> "\n  NoPageModel\n}"
}

fn generate_page_msg_type(
  routes: List(ScannedRoute),
  contract_map: dict.Dict(String, PageContract),
) -> String {
  let variants =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          Ok("  " <> route.variant_name <> "PageMsg(" <> alias <> ".Msg)")
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")
  "pub type PageMsg {\n" <> variants <> "\n}"
}

/// Generate a route pattern match expression, e.g. "router.Home" or
/// "router.ArticleSlug(slug)" depending on whether the route has params.
fn route_pattern(route: ScannedRoute) -> String {
  route_pattern_with(route, "")
}

fn route_pattern_ignored(route: ScannedRoute) -> String {
  route_pattern_with(route, "_")
}

fn route_pattern_with(route: ScannedRoute, prefix: String) -> String {
  case route.params {
    [] -> "router." <> route.variant_name
    params -> {
      let param_names =
        params
        |> list.map(fn(p) { prefix <> p.0 })
        |> string.join(", ")
      "router." <> route.variant_name <> "(" <> param_names <> ")"
    }
  }
}

/// Generate the extra arguments for init_page calls from route params.
fn route_param_args(route: ScannedRoute) -> String {
  case route.params {
    [] -> ""
    params ->
      params
      |> list.map(fn(p) { ", " <> p.0 })
      |> string.join("")
  }
}

fn generate_init_page(
  routes routes: List(ScannedRoute),
  contract_map contract_map: dict.Dict(String, PageContract),
  has_client_context has_client_context: Bool,
) -> String {
  let arms =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          let pattern = route_pattern(route)
          let param_args = route_param_args(route)
          let call_args = case has_client_context, param_args {
            True, _ -> "(" <> "client_context" <> param_args <> ")"
            False, "" -> "()"
            False, _ -> "(" <> string.drop_start(param_args, 2) <> ")"
          }
          let server_init_call = case route.params {
            [] ->
              "      transport.send_page_init(\""
              <> route.variant_name
              <> "\", Nil)\n"
            params -> {
              let param_names = list.map(params, fn(p) { p.0 })
              let params_tuple = case param_names {
                [single] -> single
                _ -> "#(" <> string.join(param_names, ", ") <> ")"
              }
              "      transport.send_page_init(\""
              <> route.variant_name
              <> "\", "
              <> params_tuple
              <> ")\n"
            }
          }
          Ok(
            "    "
            <> pattern
            <> " -> {\n"
            <> server_init_call
            <> "      let #(m, e) = "
            <> alias
            <> ".init"
            <> call_args
            <> "\n"
            <> "      #("
            <> route.variant_name
            <> "PageModel(m), effect.map(e, fn(msg) { PageMsg("
            <> route.variant_name
            <> "PageMsg(msg)) }))\n"
            <> "    }",
          )
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")

  let not_found_arm = "    _ -> #(NoPageModel, effect.none())"

  let sig = case has_client_context {
    True ->
      "fn init_page(route route: router.Route, client_context client_context: client_context.ClientContext) -> #(PageModel, Effect(Msg)) {"
    False ->
      "fn init_page(route route: router.Route) -> #(PageModel, Effect(Msg)) {"
  }

  sig <> "\n  case route {\n" <> arms <> "\n" <> not_found_arm <> "\n  }\n}"
}

fn generate_hydrate_page(
  routes routes: List(ScannedRoute),
  contract_map contract_map: dict.Dict(String, PageContract),
  has_client_context has_client_context: Bool,
) -> String {
  let hydrate_uses_client_context =
    has_client_context
    && list.any(routes, fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) -> contract.has_model
        Error(Nil) -> False
      }
    })
  let hydrate_client_context_name = case hydrate_uses_client_context {
    True -> "client_context"
    False -> "_client_context"
  }
  let error_fallback = case has_client_context {
    True ->
      "        Error(_) -> init_page(route: route, client_context: client_context)\n"
    False -> "        Error(_) -> init_page(route: route)\n"
  }
  let arms =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model && contract.has_init_loaded -> {
          let alias = page_module_alias(route)
          let pattern = route_pattern_ignored(route)
          let decoder_name = page_model_decoder_name(route.module_path)
          let init_loaded_call = case has_client_context {
            True ->
              alias
              <> ".init_loaded("
              <> hydrate_client_context_name
              <> ", model)"
            False -> alias <> ".init_loaded(model)"
          }
          let variant = route.variant_name
          Ok(
            "    "
            <> pattern
            <> " -> {\n"
            <> "      case codec.decode_flags_typed(flags, \""
            <> decoder_name
            <> "\") {\n"
            <> "        Ok(model) -> {\n"
            <> "          let #(m, e) = "
            <> init_loaded_call
            <> "\n"
            <> "          #("
            <> variant
            <> "PageModel(m), effect.map(e, fn(msg) { PageMsg("
            <> variant
            <> "PageMsg(msg)) }))\n"
            <> "        }\n"
            <> error_fallback
            <> "      }\n"
            <> "    }",
          )
        }
        Ok(contract) if contract.has_model -> {
          let pattern = route_pattern_ignored(route)
          let decoder_name = page_model_decoder_name(route.module_path)
          let variant = route.variant_name
          Ok(
            "    "
            <> pattern
            <> " -> {\n"
            <> "      case codec.decode_flags_typed(flags, \""
            <> decoder_name
            <> "\") {\n"
            <> "        Ok(model) -> #("
            <> variant
            <> "PageModel(model), effect.none())\n"
            <> error_fallback
            <> "      }\n"
            <> "    }",
          )
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")

  let sig = case has_client_context {
    True ->
      "fn hydrate_page(route: router.Route, flags: String, "
      <> hydrate_client_context_name
      <> ": client_context.ClientContext) -> #(PageModel, Effect(Msg)) {"
    False ->
      "fn hydrate_page(route: router.Route, flags: String) -> #(PageModel, Effect(Msg)) {"
  }

  sig
  <> "\n  case route {\n"
  <> arms
  <> "\n    _ -> #(NoPageModel, effect.none())\n  }\n}"
}

fn generate_reinit_server(
  routes: List(ScannedRoute),
  contract_map: dict.Dict(String, PageContract),
) -> String {
  let arms =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let pattern = route_pattern(route)
          let body = case route.params {
            [] ->
              "      transport.send_page_init(\""
              <> route.variant_name
              <> "\", Nil)"
            [single] ->
              "      transport.send_page_init(\""
              <> route.variant_name
              <> "\", "
              <> single.0
              <> ")"
            params -> {
              let tuple =
                "#("
                <> string.join(list.map(params, fn(p) { p.0 }), ", ")
                <> ")"
              "      transport.send_page_init(\""
              <> route.variant_name
              <> "\", "
              <> tuple
              <> ")"
            }
          }
          Ok(
            "    "
            <> pattern
            <> " -> {\n"
            <> body
            <> "\n      effect.none()\n    }",
          )
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")

  "fn reinit_server(route: router.Route) -> Effect(Msg) {\n  case route {\n"
  <> arms
  <> "\n    _ -> effect.none()\n  }\n}"
}

fn generate_update_page(
  routes routes: List(ScannedRoute),
  contract_map contract_map: dict.Dict(String, PageContract),
  has_client_context has_client_context: Bool,
) -> String {
  let arms =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          let vn = route.variant_name
          case has_client_context, contract.updates_client_context {
            True, True ->
              Ok(
                "    "
                <> vn
                <> "PageModel(m), "
                <> vn
                <> "PageMsg(msg) -> {\n"
                <> "      let #(new_m, e, ctx_msg) = "
                <> alias
                <> ".update(client_context, m, msg)\n"
                <> "      #("
                <> vn
                <> "PageModel(new_m), effect.map(e, fn(msg) { PageMsg("
                <> vn
                <> "PageMsg(msg)) }), ctx_msg)\n"
                <> "    }",
              )
            True, False ->
              Ok(
                "    "
                <> vn
                <> "PageModel(m), "
                <> vn
                <> "PageMsg(msg) -> {\n"
                <> "      let #(new_m, e) = "
                <> alias
                <> ".update(client_context, m, msg)\n"
                <> "      #("
                <> vn
                <> "PageModel(new_m), effect.map(e, fn(msg) { PageMsg("
                <> vn
                <> "PageMsg(msg)) }), None)\n"
                <> "    }",
              )
            _, _ ->
              Ok(
                "    "
                <> vn
                <> "PageModel(m), "
                <> vn
                <> "PageMsg(msg) -> {\n"
                <> "      let #(new_m, e) = "
                <> alias
                <> ".update(m, msg)\n"
                <> "      #("
                <> vn
                <> "PageModel(new_m), effect.map(e, fn(msg) { PageMsg("
                <> vn
                <> "PageMsg(msg)) }))\n"
                <> "    }",
              )
          }
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")

  case has_client_context {
    True -> {
      let catch_all = "    _, _ -> #(page_model, effect.none(), None)"
      let sig =
        "fn update_page(page_model page_model: PageModel, page_msg page_msg: PageMsg, client_context client_context: client_context.ClientContext) -> #(PageModel, Effect(Msg), Option(client_context.ClientContextMsg)) {"
      sig
      <> "\n  case page_model, page_msg {\n"
      <> arms
      <> "\n"
      <> catch_all
      <> "\n  }\n}"
    }
    False -> {
      let catch_all = "    _, _ -> #(page_model, effect.none())"
      let sig =
        "fn update_page(page_model page_model: PageModel, page_msg page_msg: PageMsg) -> #(PageModel, Effect(Msg)) {"
      sig
      <> "\n  case page_model, page_msg {\n"
      <> arms
      <> "\n"
      <> catch_all
      <> "\n  }\n}"
    }
  }
}

fn generate_render_page(
  routes routes: List(ScannedRoute),
  contract_map contract_map: dict.Dict(String, PageContract),
  has_client_context has_client_context: Bool,
) -> String {
  let arms =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          let vn = route.variant_name
          let view_args = case has_client_context {
            True -> "(client_context, m)"
            False -> "(m)"
          }
          Ok(
            "    "
            <> vn
            <> "PageModel(m) ->\n"
            <> "      element.map("
            <> alias
            <> ".view"
            <> view_args
            <> ", fn(msg) { PageMsg("
            <> vn
            <> "PageMsg(msg)) })",
          )
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")

  let not_found_arm =
    "    NoPageModel -> html.div([], [html.text(\"Page not found\")])"

  let sig = case has_client_context {
    True ->
      "fn render_page(page_model: PageModel, client_context: client_context.ClientContext) -> Element(Msg) {"
    False -> "fn render_page(page_model: PageModel) -> Element(Msg) {"
  }

  sig
  <> "\n  case page_model {\n"
  <> arms
  <> "\n"
  <> not_found_arm
  <> "\n  }\n}"
}

/// Generate the import alias for a page module, using the route's module_path.
/// e.g. "pages/home_" -> import alias "pages_home_"
///      "pages/article/slug_" -> import alias "pages_article_slug_"
fn page_module_alias(route: ScannedRoute) -> String {
  string.replace(route.module_path, "/", "_")
}

fn page_model_decoder_name(module_path: String) -> String {
  "decode_" <> string.replace(module_path, "/", "_") <> "_model"
}

fn last_segment(module_path: String) -> String {
  case string.split(module_path, "/") |> list.last {
    Ok(seg) -> seg
    Error(Nil) -> module_path
  }
}

fn module_alias(module_path: String) -> String {
  string.replace(module_path, "/", "_")
}

fn generate_page_imports(
  routes: List(ScannedRoute),
  contract_map: dict.Dict(String, PageContract),
) -> String {
  routes
  |> list.filter_map(fn(route) {
    case dict.get(contract_map, route.variant_name) {
      Ok(contract) if contract.has_model -> {
        let alias = page_module_alias(route)
        Ok("import " <> route.module_path <> " as " <> alias)
      }
      _ -> Error(Nil)
    }
  })
  |> list.unique
  |> list.sort(string.compare)
  |> string.join("\n")
}
