//// HTTP RPC handler codegen.
////
//// Generates http_handler.gleam: handles POST /rpc requests for
//// non-WebSocket clients. Decodes the request body through protocol_wire,
//// dispatches to the RPC handler, and returns the response. When auth is
//// configured, runs resolve/is_authenticated/authorize per request.

import gleam/bool
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/string
import justin
import libero/scanner.{type HandlerEndpoint}
import libero/wire_identity
import rally/internal/types.{
  type AuthConfig, type PageContract, type ScannedRoute, AuthConfig,
}

type PageAuthInfo {
  PageAuthInfo(
    page: String,
    module_path: String,
    required: Bool,
    has_authorize: Bool,
    wire_tag: String,
  )
}

pub fn generate(
  endpoints: List(HandlerEndpoint),
  rpc_dispatch_module: String,
  auth_config: Option(AuthConfig),
  contracts: List(#(ScannedRoute, PageContract)),
  from_session_module from_session_module: String,
  wire_import_module wire_import_module: String,
  protocol protocol: String,
) -> String {
  case auth_config {
    Some(AuthConfig(auth_module:)) ->
      generate_with_auth(
        rpc_dispatch_module,
        auth_module,
        from_session_module,
        endpoints,
        contracts,
        wire_import_module,
        protocol,
      )
    None -> generate_no_auth(rpc_dispatch_module, wire_import_module, protocol)
  }
}

fn generate_no_auth(
  _rpc_dispatch_module: String,
  wire_import_module: String,
  _protocol: String,
) -> String {
  "// Generated by Rally — do not edit.

import gleam/bytes_tree
import gleam/http/response.{type Response}
import mist.{type ResponseData}
" <> import_as(wire_import_module, "wire") <> "\n" <> "import rally/runtime/internal/effect_state
import server_context.{type ServerContext}

pub fn handle(
  body body: BitArray,
  server_context server_context: ServerContext,
  session_id session_id: String,
) -> Response(ResponseData) {
  let Nil = effect_state.put_ws_session(session_id)
  case wire.decode_rpc_envelope(body) {
    Ok(envelope) -> {
      let #(result, _new_ctx) = wire.dispatch_rpc(envelope, server_context)
      response.new(200)
      |> response.set_header(\"content-type\", wire.rpc_content_type())
      |> response.set_body(mist.Bytes(wire.rpc_result_body(result)))
    }
    Error(Nil) ->
      response.new(400)
      |> response.set_body(mist.Bytes(bytes_tree.from_string(\"Bad request\")))
  }
}
"
  |> string.trim
}

fn last_segment(module_path: String) -> String {
  case string.split(module_path, "/") |> list.last {
    Ok(seg) -> seg
    Error(Nil) -> module_path
  }
}

fn generate_with_auth(
  _rpc_dispatch_module: String,
  auth_module: String,
  from_session_module: String,
  endpoints: List(HandlerEndpoint),
  contracts: List(#(ScannedRoute, PageContract)),
  wire_import_module: String,
  protocol: String,
) -> String {
  let auth_ref = last_segment(auth_module)
  let from_session_ref = last_segment(from_session_module)

  // Build the mapping from wire variant tag to PageAuthInfo
  let page_auth_map = build_page_auth_map(endpoints, contracts, protocol)

  // Build imports
  let auth_import = import_as(auth_module, auth_ref)
  let from_session_import = case from_session_ref == "server_context" {
    True -> ""
    False -> import_as(from_session_module, from_session_ref)
  }
  let authorize_imports = generate_authorize_imports(page_auth_map)

  // Build the handle function body with auth enforcement
  let auth_checks =
    generate_auth_flow(page_auth_map, auth_ref, from_session_ref)

  "// Generated by Rally — do not edit.

import gleam/bytes_tree
import gleam/http/response.{type Response}
import mist.{type ResponseData}
import rally/runtime/internal/effect_state
import server_context.{type ServerContext}
" <> auth_import <> "
" <> import_as(wire_import_module, "wire") <> "
" <> from_session_import <> "
" <> authorize_imports <> "

type PageAuthInfo {
  PageAuthInfo(page: String, required: Bool, has_authorize: Bool)
}

pub fn handle(
  body body: BitArray,
  server_context server_context: ServerContext,
  session_id session_id: String,
  hostname hostname: String,
) -> Response(ResponseData) {
  let Nil = effect_state.put_ws_session(session_id)
  case " <> auth_ref <> ".resolve(server_context, session_id) {
    Error(Nil) ->
      response.new(500)
      |> response.set_body(mist.Bytes(bytes_tree.from_string(\"Auth service unavailable\")))
    Ok(identity) ->
" <> auth_checks <> "
  }
}
" <> generate_handler_page_info(page_auth_map) <> "
" <> generate_check_page_authorize(page_auth_map, auth_ref) <> "
"
  |> string.trim
}

fn build_page_auth_map(
  endpoints: List(HandlerEndpoint),
  contracts: List(#(ScannedRoute, PageContract)),
  protocol: String,
) -> List(PageAuthInfo) {
  list.flat_map(endpoints, fn(endpoint) {
    // Find the contract whose route module_path matches the endpoint's module_path
    case
      list.find_map(contracts, fn(pair) {
        let #(route, contract) = pair
        case route.module_path == endpoint.module_path {
          True -> Ok(#(route, contract))
          False -> Error(Nil)
        }
      })
    {
      Ok(page_contract) -> {
        let #(route, contract) = page_contract
        endpoint_wire_tags(endpoint, protocol)
        |> list.map(fn(wire_tag) {
          PageAuthInfo(
            page: route.variant_name,
            module_path: endpoint.module_path,
            required: contract.page_auth_required,
            has_authorize: contract.has_authorize,
            wire_tag: wire_tag,
          )
        })
      }
      Error(Nil) -> []
    }
  })
}

fn endpoint_wire_tags(
  endpoint: HandlerEndpoint,
  protocol: String,
) -> List(String) {
  case protocol {
    "json" -> [endpoint_json_tag(endpoint)]
    _ -> {
      let function_tag = "server_" <> endpoint.fn_name
      let hash_tags = case endpoint.msg_type {
        Some(#(module_path, type_name)) -> {
          let fields = list.map(endpoint.params, fn(param) { param.1 })
          let #(_, hash) =
            wire_identity.wire_identity(module_path, type_name, fields)
          [hash]
        }
        None -> []
      }
      list.append([function_tag], hash_tags)
    }
  }
}

fn endpoint_json_tag(endpoint: HandlerEndpoint) -> String {
  let #(module_path, type_name) = case endpoint.msg_type {
    Some(#(module_path, type_name)) -> #(module_path, type_name)
    None -> #(
      endpoint.module_path,
      justin.pascal_case("server_" <> endpoint.fn_name),
    )
  }
  module_path <> "." <> type_name
}

fn generate_authorize_imports(map: List(PageAuthInfo)) -> String {
  map
  |> list.filter(fn(info) { info.has_authorize })
  |> list.map(fn(info) {
    import_as(info.module_path, module_to_alias(info.module_path))
  })
  |> list.unique
  |> list.sort(string.compare)
  |> fn(imports) {
    case imports {
      [] -> ""
      _ -> string.join(imports, "\n") <> "\n"
    }
  }
}

fn generate_handler_page_info(map: List(PageAuthInfo)) -> String {
  let arms =
    list.map(map, fn(info) {
      "    \""
      <> info.wire_tag
      <> "\" -> Ok(PageAuthInfo(page: \""
      <> info.page
      <> "\", required: "
      <> bool_str(info.required)
      <> ", has_authorize: "
      <> bool_str(info.has_authorize)
      <> "))"
    })
    |> string.join("\n")
    |> fn(s) { s <> "\n    _ -> Error(Nil)" }

  "fn handler_page_info(variant: String) -> Result(PageAuthInfo, Nil) {
  case variant {
" <> arms <> "
  }
}"
}

fn generate_check_page_authorize(
  map: List(PageAuthInfo),
  auth_ref: String,
) -> String {
  let with_auth =
    map
    |> list.filter(fn(info) { info.has_authorize })
    |> list.map(fn(info) { #(info.page, info.module_path) })
    |> list.unique
  case with_auth {
    [] -> ""
    _ -> {
      let arms =
        list.map(with_auth, fn(info) {
          let #(page, module_path) = info
          "    \""
          <> page
          <> "\" -> "
          <> module_to_alias(module_path)
          <> ".authorize(server_context, identity)"
        })
        |> string.join("\n")
        |> fn(s) { s <> "\n    _ -> False" }

      "
fn check_page_authorize(page: String, server_context: ServerContext, identity: " <> auth_ref <> ".Identity) -> Bool {
  case page {
" <> arms <> "
  }
}"
    }
  }
}

fn generate_auth_flow(
  map: List(PageAuthInfo),
  auth_ref: String,
  from_session_ref: String,
) -> String {
  let decode_and_lookup =
    "      case wire.decode_rpc_envelope(body) {
        Ok(envelope) ->
          case handler_page_info(wire.rpc_identity(envelope)) {
                Error(Nil) -> {
                  let result =
                    wire.error_result(wire.rpc_request_id(envelope), \"Unknown RPC\")
                  response.new(400)
                  |> response.set_header(\"content-type\", wire.rpc_content_type())
                  |> response.set_body(mist.Bytes(wire.rpc_result_body(result)))
                }
                Ok(info) -> {
                  let page = info.page
                  let required = info.required
                  let has_authorize = info.has_authorize"

  let is_auth_check = "
                  case required && !" <> auth_ref <> ".is_authenticated(identity) {
                    True -> {
                      let result =
                        wire.auth_error_result(wire.rpc_request_id(envelope), \"Authentication required\")
                      response.new(401)
                      |> response.set_header(\"content-type\", wire.rpc_content_type())
                      |> response.set_body(mist.Bytes(wire.rpc_result_body(result)))
                    }
                    False -> {"

  let from_session = "
                      let #(_, server_context) = " <> from_session_ref <> ".from_session(server_context: server_context, session_id: session_id, hostname: hostname, identity: identity)"

  let authorize_check =
    "
                      case has_authorize && !check_page_authorize(page, server_context, identity) {
                        True -> {
                          let result =
                            wire.auth_error_result(wire.rpc_request_id(envelope), \"Forbidden\")
                          response.new(403)
                          |> response.set_header(\"content-type\", wire.rpc_content_type())
                          |> response.set_body(mist.Bytes(wire.rpc_result_body(result)))
                        }
                        False -> {"

  let dispatch =
    "
                        let #(result, _new_ctx) = wire.dispatch_rpc(envelope, server_context, identity)
                        response.new(200)
                        |> response.set_header(\"content-type\", wire.rpc_content_type())
                        |> response.set_body(mist.Bytes(wire.rpc_result_body(result)))"

  let close_page_info =
    "
                }
              }
        Error(Nil) ->
          response.new(400)
          |> response.set_body(mist.Bytes(bytes_tree.from_string(\"Bad request\")))
      }"

  let has_any_required = list.any(map, fn(info) { info.required })
  let has_any_authorize = list.any(map, fn(info) { info.has_authorize })

  let auth_open = case has_any_required {
    True -> is_auth_check
    False ->
      "
                  {"
  }
  let auth_close = case has_any_required {
    True ->
      "
                    }
                  }"
    False ->
      "
                  }"
  }
  let authorize_open = case has_any_authorize {
    True -> authorize_check
    False ->
      "
                      {"
  }
  let authorize_close = case has_any_authorize {
    True ->
      "
                      }
                    }"
    False ->
      "
                      }"
  }

  decode_and_lookup
  <> auth_open
  <> from_session
  <> authorize_open
  <> dispatch
  <> authorize_close
  <> auth_close
  <> close_page_info
}

fn module_to_alias(module_path: String) -> String {
  string.replace(module_path, "/", "_")
}

fn bool_str(b: Bool) -> String {
  bool.to_string(b)
}

fn import_as(module_path: String, alias: String) -> String {
  case last_segment(module_path) == alias {
    True -> "import " <> module_path
    False -> "import " <> module_path <> " as " <> alias
  }
}
