//// SSR handler codegen.
////
//// Generates ssr_handler.gleam: takes a parsed Route, calls the page's
//// load function, renders view wrapped in layout, embeds the model as
//// base64 flags for client hydration. Handles auth resolve, from_session,
//// authorize, and LoadResult (Page/Redirect with cookies) when auth is
//// configured.

import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/regexp
import gleam/string
import rally/internal/types.{
  type AuthConfig, type PageContract, type ScannedRoute, AuthConfig,
}

const client_script_marker = "{{rally_client_script}}"

const client_script_path = "/_build/client/generated/app.mjs"

const generated_app_path_pattern = "(['\"])/_build/[^'\"]+/generated/app\\.mjs(['\"])"

pub fn generate(
  page_contracts page_contracts: List(#(ScannedRoute, PageContract)),
  has_client_context has_client_context: Bool,
  has_from_session has_from_session: Bool,
  from_session_module from_session_module: String,
  router_module router_module: String,
  shell_html shell_html: String,
  atoms_module atoms_module: String,
  wire_module wire_module: Option(String),
  client_context_module client_context_module: Option(String),
  auth_config auth_config: Option(AuthConfig),
  wire_import_module wire_import_module: String,
  protocol protocol: String,
) -> String {
  let use_session = has_client_context && has_from_session
  let is_json = protocol == "json"
  let json_codecs_module = case is_json {
    True -> string.replace(wire_import_module, "/protocol_wire", "/json_codecs")
    False -> ""
  }
  let from_session_ref = last_segment(from_session_module)
  let has_auth = option.is_some(auth_config)
  let auth_module_ref = case auth_config {
    Some(AuthConfig(auth_module:)) -> last_segment(auth_module)
    None -> ""
  }

  let load_arms =
    generate_load_arms(
      page_contracts: page_contracts,
      has_client_context: has_client_context,
      use_session: use_session,
      has_from_session: has_from_session,
      from_session_module: from_session_ref,
      wire_module: wire_module,
      auth_config: auth_config,
      is_json:,
    )
  let has_load_pages = load_arms != ""

  let all_routes_have_load =
    list.all(page_contracts, fn(pair) {
      let #(_, contract) = pair
      contract.has_load && contract.has_model
    })

  let layout_imports = generate_layout_imports(page_contracts)
  let page_imports = generate_page_imports(page_contracts)

  let needs_server_context = use_session || has_load_pages
  let needs_from_session_import =
    use_session || { has_auth && has_from_session }
  let needs_codec = use_session || has_load_pages

  let base_imports =
    "// Generated by Rally — do not edit.\n\nimport gleam/bytes_tree\nimport gleam/http/response\nimport mist.{type ResponseData}\n"
    <> import_as(router_module, "router")
    <> "\nimport rally/runtime/internal/browser_env\n\n@external(erlang, \""
    <> atoms_module
    <> "\", \"ensure\")\nfn ensure_atoms() -> Nil\n"

  let server_imports = case needs_server_context {
    True ->
      "import server_context.{type ServerContext}\n"
      <> case
        needs_from_session_import && from_session_module != "server_context"
      {
        True -> import_as(from_session_module, from_session_ref) <> "\n"
        False -> ""
      }
    False -> ""
  }
  let client_context_imports = case has_client_context, client_context_module {
    True, Some(mod) -> import_as(mod, "client_context") <> "\n"
    _, _ -> ""
  }
  let codec_imports = case needs_codec {
    True -> import_as(wire_import_module, "libero_wire") <> "\n"
    False -> ""
  }
  let json_codec_imports = case is_json && needs_codec {
    True -> import_as(json_codecs_module, "json_codecs") <> "\n"
    False -> ""
  }
  let load_page_imports = case has_load_pages {
    True -> "import gleam/result\nimport gleam/string\nimport lustre/element\n"
    False -> ""
  }

  let auth_imports = case auth_config {
    Some(AuthConfig(auth_module:)) ->
      import_as(auth_module, auth_module_ref)
      <> case has_load_pages {
        True ->
          "\nimport rally/runtime/auth as rally_auth\nimport gleam/int\nimport gleam/list\n"
        False -> "\n"
      }
    _ -> ""
  }

  let wire_externals =
    generate_wire_externals(
      wire_module:,
      client_context_module:,
      has_client_context:,
      page_contracts:,
      is_json:,
    )

  let header =
    base_imports
    <> server_imports
    <> client_context_imports
    <> codec_imports
    <> json_codec_imports
    <> load_page_imports
    <> auth_imports
    <> layout_imports
    <> page_imports
    <> wire_externals

  let route_arg = case has_load_pages {
    True -> "route route: router.Route,"
    False -> "route _route: router.Route,"
  }

  let uses_session_params = has_auth || use_session
  let session_id_param = case uses_session_params {
    True -> "session_id session_id: String,"
    False -> "session_id _session_id: String,"
  }
  let hostname_param = case uses_session_params {
    True -> "hostname hostname: String,"
    False -> "hostname _hostname: String,"
  }
  let fn_params = case needs_server_context {
    True -> "
pub fn handle_request(
  " <> route_arg <> "
  server_context server_context: ServerContext,
  " <> session_id_param <> "
  " <> hostname_param <> "
) -> response.Response(ResponseData) {"
    False ->
      "
pub fn handle_request(
  _route: router.Route,
) -> response.Response(ResponseData) {"
  }

  let cc_encode_line = case wire_module, client_context_module, is_json {
    Some(_), Some(cc_mod), False -> {
      let qual = qualified_wire_name(cc_mod, "ClientContext")
      "  let client_context = wire_encode_" <> qual <> "(client_context)\n"
    }
    _, Some(cc_mod), True -> {
      let qual = qualified_wire_name(cc_mod, "ClientContext")
      "  let client_context = json_codecs.json_encode_"
      <> qual
      <> "(client_context)\n"
    }
    _, _, _ -> ""
  }
  let ctx_script = case use_session {
    True -> "
fn context_script(client_context: client_context.ClientContext) -> String {
" <> cc_encode_line <> "  let encoded = libero_wire.encode_flags(client_context)
  \"<script>window.__RALLY_CLIENT_CONTEXT__='\" <> encoded <> \"'</script>\"
}
"
    False -> ""
  }

  let shell_call = case use_session {
    True ->
      "serve_html_shell(server_context: server_context, session_id: session_id, hostname: hostname)"
    False -> "serve_html_shell()"
  }

  let fn_body = case has_load_pages {
    True -> {
      let fallback = case all_routes_have_load {
        True -> ""
        False -> "\n    _ -> " <> shell_call
      }
      fn_params <> "
  ensure_atoms()
  case route {\n" <> load_arms <> "
    router.NotFound(_) ->
      response.new(404)
      |> response.set_body(mist.Bytes(bytes_tree.from_string(\"Not found\")))" <> fallback <> "
  }
}"
    }
    False -> fn_params <> "
  ensure_atoms()
  " <> shell_call <> "
}"
  }

  let dark_mode_script =
    "<script>(function(){var c=document.cookie;if(c.includes('__rally_dark_mode=1')||(!c.includes('__rally_dark_mode=')&&window.matchMedia('(prefers-color-scheme:dark)').matches)){document.documentElement.classList.add('dark')}})()</script>"
  let shell_with_client = ensure_client_script(shell_html)
  let shell_with_dark =
    string.replace(shell_with_client, "</head>", dark_mode_script <> "</head>")
  let escaped_shell =
    shell_with_dark
    |> string.replace("\\", "\\\\")
    |> string.replace("\"", "\\\"")
    |> string.replace("\n", "\\n")

  let needs_shell_fn = case has_load_pages {
    True -> !all_routes_have_load
    False -> True
  }

  let shell_fn = case needs_shell_fn {
    False -> ""
    True ->
      case use_session, has_auth {
        True, True -> "
fn serve_html_shell(server_context server_context: ServerContext, session_id session_id: String, hostname hostname: String) -> response.Response(ResponseData) {
  case " <> auth_module_ref <> ".resolve(server_context, session_id) {
    Error(Nil) ->
      response.new(500)
      |> response.set_body(mist.Bytes(bytes_tree.from_string(\"Auth service unavailable\")))
    Ok(identity) -> {
      let #(client_context, _) = " <> from_session_ref <> ".from_session(server_context: server_context, session_id: session_id, hostname: hostname, identity: identity)
      let html = \"" <> escaped_shell <> "\" <> browser_env.script() <> context_script(client_context)
      response.new(200)
      |> response.set_header(\"content-type\", \"text/html\")
      |> response.set_body(mist.Bytes(bytes_tree.from_string(html)))
    }
  }
}
"
        True, False -> "
fn serve_html_shell(server_context server_context: ServerContext, session_id session_id: String, hostname hostname: String) -> response.Response(ResponseData) {
  let #(client_context, _) = " <> from_session_ref <> ".from_session(server_context: server_context, session_id: session_id, hostname: hostname)
  let html = \"" <> escaped_shell <> "\" <> browser_env.script() <> context_script(client_context)
  response.new(200)
  |> response.set_header(\"content-type\", \"text/html\")
  |> response.set_body(mist.Bytes(bytes_tree.from_string(html)))
}
"
        False, _ -> "
fn serve_html_shell() -> response.Response(ResponseData) {
  let html = \"" <> escaped_shell <> "\" <> browser_env.script()
  response.new(200)
  |> response.set_header(\"content-type\", \"text/html\")
  |> response.set_body(mist.Bytes(bytes_tree.from_string(html)))
}
"
      }
  }

  let shell_html_fn = case has_load_pages {
    True -> "
fn shell_html() -> String {
  \"" <> escaped_shell <> "\"
}
"
    False -> ""
  }

  let cookies_helper = case has_auth && has_load_pages {
    True ->
      "
fn apply_cookies(resp: response.Response(ResponseData), cookies: List(rally_auth.Cookie)) -> response.Response(ResponseData) {
  list.fold(cookies, resp, fn(resp, cookie) {
    case cookie {
      rally_auth.SetCookie(name, value, max_age) ->
        response.prepend_header(resp, \"set-cookie\",
          name <> \"=\" <> value <> \"; Path=/; HttpOnly; SameSite=Lax; Max-Age=\" <> int.to_string(max_age))
      rally_auth.ClearCookie(name) ->
        response.prepend_header(resp, \"set-cookie\",
          name <> \"=; Path=/; HttpOnly; Max-Age=0\")
    }
  })
}
"
    False -> ""
  }

  header
  <> fn_body
  <> ctx_script
  <> shell_fn
  <> shell_html_fn
  <> cookies_helper
  <> marker_helper(has_load_pages)
}

fn marker_helper(has_load_pages: Bool) -> String {
  case has_load_pages {
    True -> {
      let body = [
        "fn insert_rendered(shell: String, rendered: String) -> String {",
        "  case find_app_marker(shell) {",
        "    Ok(marker) -> string.replace(shell, marker, marker <> rendered)",
        "    Error(Nil) -> shell",
        "  }",
        "}",
        "",
        "fn find_app_marker(shell: String) -> Result(String, Nil) {",
        "  // Find the element with id=app (any tag, any attributes, any quoting).",
        "  let id_dq = \"id=\\\"app\\\"\"",
        "  let id_sq = \"id='app'\"",
        "  let id_dq_spaced = \"id = \\\"app\\\"\"",
        "  let id_sq_spaced = \"id = 'app'\"",
        "  let id_attr = case string.contains(shell, id_dq) {",
        "    True -> Ok(id_dq)",
        "    False -> case string.contains(shell, id_sq) {",
        "      True -> Ok(id_sq)",
        "      False -> case string.contains(shell, id_dq_spaced) {",
        "        True -> Ok(id_dq_spaced)",
        "        False -> case string.contains(shell, id_sq_spaced) {",
        "          True -> Ok(id_sq_spaced)",
        "          False -> Error(Nil)",
        "        }",
        "      }",
        "    }",
        "  }",
        "  use id_attr <- result.try(id_attr)",
        "  use #(before_id, after_id) <- result.try(string.split_once(shell, id_attr))",
        "  let reversed_before = string.reverse(before_id)",
        "  use #(after_lt_rev, _) <- result.try(string.split_once(reversed_before, \"<\"))",
        "  let tag_start = \"<\" <> string.reverse(after_lt_rev)",
        "  use #(tag_end, _) <- result.try(string.split_once(after_id, \">\"))",
        "  Ok(tag_start <> id_attr <> tag_end <> \">\")",
        "}",
      ]
      "\n" <> string.join(body, "\n") <> "\n"
    }
    _ -> ""
  }
}

fn import_as(module_path: String, alias: String) -> String {
  case last_segment(module_path) == alias {
    True -> "import " <> module_path
    False -> "import " <> module_path <> " as " <> alias
  }
}

fn generate_page_imports(
  page_contracts: List(#(ScannedRoute, PageContract)),
) -> String {
  page_contracts
  |> list.filter_map(fn(pair) {
    let #(route, contract) = pair
    case contract.has_load && contract.has_model {
      True -> {
        let alias = module_to_alias(route.module_path)
        Ok("import " <> route.module_path <> " as " <> alias)
      }
      False -> Error(Nil)
    }
  })
  |> list.unique
  |> list.sort(string.compare)
  |> fn(imports) {
    case imports {
      [] -> ""
      _ -> string.join(imports, "\n") <> "\n"
    }
  }
}

fn module_to_alias(module_path: String) -> String {
  string.replace(module_path, "/", "_")
}

fn last_segment(module_path: String) -> String {
  case string.split(module_path, "/") |> list.last {
    Ok(seg) -> seg
    Error(Nil) -> module_path
  }
}

fn generate_layout_imports(
  page_contracts: List(#(ScannedRoute, PageContract)),
) -> String {
  page_contracts
  |> list.filter_map(fn(pair) {
    let #(route, contract) = pair
    case contract.has_load && contract.has_model, route.layout_module {
      True, Some(layout) ->
        Ok("import " <> layout <> " as " <> module_to_alias(layout))
      _, _ -> Error(Nil)
    }
  })
  |> list.unique
  |> list.sort(string.compare)
  |> fn(imports) {
    case imports {
      [] -> ""
      _ -> string.join(imports, "\n") <> "\n"
    }
  }
}

fn ensure_client_script(shell_html: String) -> String {
  let shell_html = rewrite_generated_app_paths(shell_html)
  case string.contains(shell_html, client_script_marker) {
    True ->
      string.replace(shell_html, client_script_marker, client_script_tag())
    False ->
      case string.contains(shell_html, client_script_path) {
        True -> shell_html
        False -> inject_client_script(shell_html)
      }
  }
}

fn rewrite_generated_app_paths(shell_html: String) -> String {
  case regexp.from_string(generated_app_path_pattern) {
    Ok(pattern) ->
      regexp.match_map(pattern, in: shell_html, with: fn(match) {
        case match.submatches {
          [Some(open_quote), Some(close_quote)] ->
            open_quote <> client_script_path <> close_quote
          _ -> match.content
        }
      })
    Error(_) -> shell_html
  }
}

fn inject_client_script(shell_html: String) -> String {
  case string.contains(shell_html, "</body>") {
    True ->
      string.replace(shell_html, "</body>", client_script_tag() <> "</body>")
    False -> shell_html <> client_script_tag()
  }
}

fn client_script_tag() -> String {
  "<script type=\"module\">
    import { main } from \"" <> client_script_path <> "\";
    main();
  </script>"
}

fn generate_load_arms(
  page_contracts page_contracts: List(#(ScannedRoute, PageContract)),
  has_client_context has_client_context: Bool,
  use_session use_session: Bool,
  has_from_session has_from_session: Bool,
  from_session_module from_session_module: String,
  wire_module wire_module: Option(String),
  auth_config auth_config: Option(AuthConfig),
  is_json is_json: Bool,
) -> String {
  let auth_module_ref = case auth_config {
    Some(AuthConfig(auth_module:)) -> last_segment(auth_module)
    None -> ""
  }
  page_contracts
  |> list.filter_map(fn(pair) {
    let #(route, contract) = pair
    case contract.has_load && contract.has_model {
      True -> {
        let alias = module_to_alias(route.module_path)
        let pattern = route_pattern_for_load(route)
        let load_args =
          route.params
          |> list.map(fn(p) { p.0 })
          |> string.join(", ")
        let has_params = route.params != []
        let has_auth = option.is_some(auth_config)
        let needs_fs_for_auth = has_from_session

        let identity_arg = case has_auth {
          True ->
            case has_params {
              True -> ", server_context, identity"
              False -> "server_context, identity"
            }
          False ->
            case has_params {
              True -> ", server_context"
              False -> "server_context"
            }
        }
        let from_session_call = case has_auth {
          True ->
            from_session_module
            <> ".from_session(server_context: server_context, session_id: session_id, hostname: hostname, identity: identity)"
          False ->
            from_session_module
            <> ".from_session(server_context: server_context, session_id: session_id, hostname: hostname)"
        }
        // Auth requires from_session to enrich ServerContext before
        // authorize and load, regardless of whether ClientContext exists.
        let needs_from_session =
          use_session || { has_auth && needs_fs_for_auth }
        let ctx_init = case needs_from_session {
          True ->
            case has_client_context {
              True ->
                "      let #(client_context, server_context) = "
                <> from_session_call
                <> "\n"
              False ->
                "      let #(_, server_context) = " <> from_session_call <> "\n"
            }
          False ->
            case has_client_context {
              True -> "      let #(client_context, _) = client_context.init()\n"
              False -> ""
            }
        }
        let view_call = case has_client_context {
          True -> alias <> ".view(client_context, model)"
          False -> alias <> ".view(model)"
        }
        let view_expr = case route.layout_module, has_client_context {
          Some(layout), True -> {
            let layout_alias = module_to_alias(layout)
            "    let page_view = element.map("
            <> view_call
            <> ", fn(_) { Nil })\n"
            <> "    let rendered = element.to_string("
            <> layout_alias
            <> ".layout(client_context, fn(_) { Nil }, page_view))\n"
          }
          Some(layout), False -> {
            let layout_alias = module_to_alias(layout)
            "    let page_view = element.map("
            <> view_call
            <> ", fn(_) { Nil })\n"
            <> "    let rendered = element.to_string("
            <> layout_alias
            <> ".layout(page_view))\n"
          }
          None, _ ->
            "    let rendered = element.to_string(" <> view_call <> ")\n"
        }
        let ctx_script = case use_session {
          True -> "      let ctx_tag = context_script(client_context)\n"
          False -> ""
        }
        let flags_target = case contract.has_init_loaded {
          True -> "data"
          False -> "model"
        }
        let wire_encode_flags = case wire_module, is_json {
          Some(_), False -> {
            let qual = qualified_wire_name(route.module_path, "Model")
            "      let "
            <> flags_target
            <> " = wire_encode_"
            <> qual
            <> "("
            <> flags_target
            <> ")\n"
          }
          Some(_), True -> {
            let qual = qualified_wire_name(route.module_path, "Model")
            "      let "
            <> flags_target
            <> " = json_codecs.json_encode_"
            <> qual
            <> "("
            <> flags_target
            <> ")\n"
          }
          None, _ -> ""
        }
        let flags_line =
          wire_encode_flags
          <> "      let flags = libero_wire.encode_flags("
          <> flags_target
          <> ")\n"
          <> "      let flags_tag = \"<script>window.__RALLY_FLAGS__='\" <> flags <> \"'</script>\"\n"
        let full_html_line = case use_session {
          True ->
            "      let shell = shell_html()\n      let full_html = insert_rendered(shell, rendered)\n        <> browser_env.script() <> ctx_tag <> flags_tag\n"
          False ->
            "      let shell = shell_html()\n      let full_html = insert_rendered(shell, rendered)\n        <> browser_env.script() <> flags_tag\n"
        }

        let render_body =
          ctx_init
          <> "      let "
          <> flags_target
          <> " = "
          <> alias
          <> ".load("
          <> load_args
          <> identity_arg
          <> ")\n"
          <> case contract.has_init_loaded, has_client_context {
            True, True ->
              "      let #(model, _) = "
              <> alias
              <> ".init_loaded(client_context, data)\n"
            True, False ->
              "      let #(model, _) = " <> alias <> ".init_loaded(data)\n"
            False, _ -> ""
          }
          <> "      "
          <> view_expr
          <> ctx_script
          <> flags_line
          <> full_html_line
          <> "      response.new(200)\n"
          <> "      |> response.set_header(\"content-type\", \"text/html\")\n"
          <> "      |> response.set_body(mist.Bytes(bytes_tree.from_string(full_html)))\n"

        // For auth-enabled pages, wrap in resolve + checks + LoadResult handling
        let arm_body = case has_auth {
          True -> {
            let resolve_open =
              "      case "
              <> auth_module_ref
              <> ".resolve(server_context, session_id) {\n"
              <> "        Error(Nil) ->\n"
              <> "          response.new(500)\n"
              <> "          |> response.set_body(mist.Bytes(bytes_tree.from_string(\"Auth service unavailable\")))\n"
              <> "        Ok(identity) -> {\n"
            let is_auth_check = case contract.page_auth_required {
              True ->
                "          case "
                <> auth_module_ref
                <> ".is_authenticated(identity) {\n"
                <> "            False -> response.new(302)\n"
                <> "              |> response.set_header(\"location\", "
                <> auth_module_ref
                <> ".redirect_url)\n"
                <> "              |> response.set_body(mist.Bytes(bytes_tree.from_string(\"\")))\n"
                <> "            True -> {\n"
              False -> ""
            }
            let authorize_check = case contract.has_authorize {
              True ->
                "              case "
                <> alias
                <> ".authorize(server_context, identity) {\n"
                <> "                False -> response.new(403)\n"
                <> "                  |> response.set_body(mist.Bytes(bytes_tree.from_string(\"Forbidden\")))\n"
                <> "                True -> {\n"
              False -> ""
            }

            // The load+render block, wrapped in LoadResult case.
            // When has_init_loaded is False, "data" from the LoadResult
            // pattern IS the model — no init_loaded call to produce "model".
            let model_var = case contract.has_init_loaded {
              True -> "model"
              False -> "data"
            }
            let view_call_auth = case has_client_context {
              True -> alias <> ".view(client_context, " <> model_var <> ")"
              False -> alias <> ".view(" <> model_var <> ")"
            }
            let view_expr_auth = case route.layout_module, has_client_context {
              Some(layout), True -> {
                let layout_alias = module_to_alias(layout)
                "    let page_view = element.map("
                <> view_call_auth
                <> ", fn(_) { Nil })\n"
                <> "    let rendered = element.to_string("
                <> layout_alias
                <> ".layout(client_context, fn(_) { Nil }, page_view))\n"
              }
              Some(layout), False -> {
                let layout_alias = module_to_alias(layout)
                "    let page_view = element.map("
                <> view_call_auth
                <> ", fn(_) { Nil })\n"
                <> "    let rendered = element.to_string("
                <> layout_alias
                <> ".layout(page_view))\n"
              }
              None, _ ->
                "    let rendered = element.to_string("
                <> view_call_auth
                <> ")\n"
            }
            let wire_encode_flags_auth = case wire_module, is_json {
              Some(_), False -> {
                let qual = qualified_wire_name(route.module_path, "Model")
                "      let "
                <> model_var
                <> " = wire_encode_"
                <> qual
                <> "("
                <> model_var
                <> ")\n"
              }
              Some(_), True -> {
                let qual = qualified_wire_name(route.module_path, "Model")
                "      let "
                <> model_var
                <> " = json_codecs.json_encode_"
                <> qual
                <> "("
                <> model_var
                <> ")\n"
              }
              None, _ -> ""
            }
            let flags_line_auth =
              wire_encode_flags_auth
              <> "      let flags = libero_wire.encode_flags("
              <> model_var
              <> ")\n"
              <> "      let flags_tag = \"<script>window.__RALLY_FLAGS__='\" <> flags <> \"'</script>\"\n"
            let load_result_block =
              ctx_init
              <> "                  case "
              <> alias
              <> ".load("
              <> load_args
              <> identity_arg
              <> ") {\n"
              <> "                    rally_auth.Page(data, cookies) -> {\n"
              <> case contract.has_init_loaded, has_client_context {
                True, True ->
                  "                      let #(model, _) = "
                  <> alias
                  <> ".init_loaded(client_context, data)\n"
                True, False ->
                  "                      let #(model, _) = "
                  <> alias
                  <> ".init_loaded(data)\n"
                False, _ -> ""
              }
              <> "                      "
              <> view_expr_auth
              <> ctx_script
              <> flags_line_auth
              <> full_html_line
              <> "                      apply_cookies(\n"
              <> "                        response.new(200)\n"
              <> "                        |> response.set_header(\"content-type\", \"text/html\")\n"
              <> "                        |> response.set_body(mist.Bytes(bytes_tree.from_string(full_html))),\n"
              <> "                        cookies,\n"
              <> "                      )\n"
              <> "                    }\n"
              <> "                    rally_auth.Redirect(url, cookies) ->\n"
              <> "                      apply_cookies(\n"
              <> "                        response.new(302)\n"
              <> "                        |> response.set_header(\"location\", url)\n"
              <> "                        |> response.set_body(mist.Bytes(bytes_tree.from_string(\"\"))),\n"
              <> "                        cookies,\n"
              <> "                      )\n"
              <> "                  }\n"

            let close_authorize = case contract.has_authorize {
              True -> "                }\n              }\n"
              False -> ""
            }
            let close_is_auth = case contract.page_auth_required {
              True -> "            }\n          }\n"
              False -> ""
            }
            let close_resolve = "        }\n      }\n"

            resolve_open
            <> is_auth_check
            <> authorize_check
            <> load_result_block
            <> close_authorize
            <> close_is_auth
            <> close_resolve
          }
          False -> render_body
        }

        Ok(
          "    router."
          <> route.variant_name
          <> pattern
          <> " -> {\n"
          <> arm_body
          <> "    }",
        )
      }
      False -> Error(Nil)
    }
  })
  |> string.join("\n")
}

fn route_pattern_for_load(route: ScannedRoute) -> String {
  case route.params {
    [] -> ""
    params -> {
      let names = list.map(params, fn(p) { p.0 })
      "(" <> string.join(names, ", ") <> ")"
    }
  }
}

fn generate_wire_externals(
  wire_module wire_module: Option(String),
  client_context_module client_context_module: Option(String),
  has_client_context has_client_context: Bool,
  page_contracts page_contracts: List(#(ScannedRoute, PageContract)),
  is_json is_json: Bool,
) -> String {
  case wire_module, is_json {
    None, _ -> ""
    _, True -> ""
    Some(mod), False -> {
      let cc_ext = case has_client_context, client_context_module {
        True, Some(cc_mod) -> {
          let qual = qualified_wire_name(cc_mod, "ClientContext")
          "\n@external(erlang, \""
          <> mod
          <> "\", \"encode_"
          <> qual
          <> "\")\nfn wire_encode_"
          <> qual
          <> "(value: a) -> b\n"
        }
        _, _ -> ""
      }
      let model_exts =
        page_contracts
        |> list.filter_map(fn(pair) {
          let #(route, contract) = pair
          case contract.has_load && contract.has_model {
            True -> {
              let qual = qualified_wire_name(route.module_path, "Model")
              Ok(
                "@external(erlang, \""
                <> mod
                <> "\", \"encode_"
                <> qual
                <> "\")\nfn wire_encode_"
                <> qual
                <> "(value: a) -> b\n",
              )
            }
            False -> Error(Nil)
          }
        })
        |> list.unique
        |> string.join("\n")
      cc_ext <> "\n" <> model_exts
    }
  }
}

fn qualified_wire_name(module_path: String, type_name: String) -> String {
  string.replace(module_path, "/", "_") <> "__" <> to_snake_case(type_name)
}

fn to_snake_case(name: String) -> String {
  let graphemes = string.to_graphemes(name)
  do_snake_case(remaining: graphemes, acc: "", prev_lower: False)
}

fn do_snake_case(
  remaining remaining: List(String),
  acc acc: String,
  prev_lower prev_lower: Bool,
) -> String {
  case remaining {
    [] -> acc
    [g, ..rest] -> {
      let lower = string.lowercase(g)
      case lower != g {
        True -> {
          let sep = case prev_lower {
            True -> "_"
            False -> ""
          }
          do_snake_case(
            remaining: rest,
            acc: acc <> sep <> lower,
            prev_lower: False,
          )
        }
        False -> do_snake_case(remaining: rest, acc: acc <> g, prev_lower: True)
      }
    }
  }
}
