//// WebSocket handler codegen.
////
//// Generates ws_handler.gleam: connection init (with optional auth resolve),
//// frame decoding via protocol_wire, page-init handling (topic subscription,
//// auth policy checks), RPC dispatch, push frame delivery, and reauth on
//// stale sessions. The output wires together page dispatch, libero RPC
//// dispatch, and the system message logger.

import gleam/bool
import gleam/int
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/string
import libero/scanner.{type HandlerEndpoint}
import libero/wire_identity
import rally/internal/generator/json_rpc_dispatch
import rally/internal/types.{
  type AuthConfig, type PageContract, type ScannedRoute, AuthConfig,
}

pub fn generate(
  page_contracts: List(#(ScannedRoute, PageContract)),
  atoms_module: String,
  _rpc_dispatch_module: String,
  auth_config: Option(AuthConfig),
  from_session_module from_session_module: String,
  endpoints endpoints: List(HandlerEndpoint),
  wire_import_module wire_import_module: String,
  protocol protocol: String,
) -> String {
  generate_with_client_context(
    page_contracts,
    atoms_module,
    "",
    auth_config,
    from_session_module:,
    endpoints:,
    wire_import_module:,
    protocol:,
    has_client_context: False,
  )
}

pub fn generate_with_client_context(
  page_contracts page_contracts: List(#(ScannedRoute, PageContract)),
  atoms_module atoms_module: String,
  rpc_dispatch_module _rpc_dispatch_module: String,
  auth_config auth_config: Option(AuthConfig),
  from_session_module from_session_module: String,
  endpoints endpoints: List(HandlerEndpoint),
  wire_import_module wire_import_module: String,
  protocol protocol: String,
  has_client_context has_client_context: Bool,
) -> String {
  let has_auth = option.is_some(auth_config)
  let has_endpoints = !list.is_empty(endpoints)
  let auth_module_ref = case auth_config {
    Some(AuthConfig(auth_module:)) -> last_segment(auth_module)
    None -> ""
  }
  let from_session_ref = last_segment(from_session_module)
  let server_effects = stateful_pages(page_contracts)
  let has_server_effects = !list.is_empty(server_effects) && protocol != "json"

  let auth_imports = case auth_config {
    Some(AuthConfig(auth_module:)) ->
      import_as(auth_module, auth_module_ref)
      <> "\n"
      <> case from_session_ref == "server_context" {
        True -> ""
        False -> import_as(from_session_module, from_session_ref) <> "\n"
      }
    None -> ""
  }

  let system_import = case has_auth && !has_endpoints {
    True -> ""
    False -> "import rally/runtime/internal/system_db\n"
  }
  let effect_runner_import = case has_server_effects {
    True -> "import rally/runtime/internal/effect_runner\n"
    False -> ""
  }
  let dynamic_import = case has_server_effects {
    True -> "import gleam/dynamic\n"
    False -> ""
  }
  let page_imports =
    server_effects
    |> list.map(fn(page) {
      let #(route, _, alias) = page
      import_as(route.module_path, alias)
    })
    |> list.unique
    |> string.join("\n")
    |> fn(s) {
      case s {
        "" -> ""
        _ -> s <> "\n"
      }
    }

  let json_imports = case protocol {
    "json" -> "import libero/json/error.{JsonError}\n"
    _ -> ""
  }

  let bit_array_import = case protocol {
    "json" -> ""
    _ -> "import gleam/bit_array\n"
  }
  let option_import = case protocol {
    "json" -> "import gleam/option.{None, Some}\n"
    _ -> "import gleam/option.{Some}\n"
  }
  let time_imports = "import gleam/time/duration\nimport gleam/time/timestamp\n"
  let header =
    "// Generated by Rally — do not edit.\n\nimport gleam/bool\n"
    <> bit_array_import
    <> dynamic_import
    <> time_imports
    <> "import gleam/int\nimport gleam/io\nimport gleam/list\n"
    <> option_import
    <> "import gleam/erlang/process\nimport rally/runtime/internal/effect_state\nimport rally/runtime/env\n"
    <> import_as(wire_import_module, "wire")
    <> "\n"
    <> effect_runner_import
    <> page_imports
    <> "import rally/runtime/topics\n"
    <> system_import
    <> "import server_context.{type ServerContext}\nimport mist.{type WebsocketConnection, type WebsocketMessage}\n"
    <> auth_imports
    <> json_imports
    <> "\n@external(erlang, \""
    <> atoms_module
    <> "\", \"ensure\")\nfn ensure_atoms() -> Nil\n"

  let init = case has_auth {
    True -> generate_init_with_auth(auth_module_ref, from_session_ref)
    False -> generate_init_no_auth()
  }
  let handler = case has_auth {
    True ->
      generate_frame_handler_with_auth(
        page_contracts,
        auth_module_ref,
        from_session_ref,
        endpoints,
        protocol,
        has_client_context,
      )
    False ->
      generate_frame_handler_no_auth(
        page_contracts,
        protocol,
        has_client_context,
      )
  }
  string.join([header, init, handler], "\n\n") <> "\n"
}

// -- Init (no auth) --

fn generate_init_no_auth() -> String {
  "pub fn on_init(
  conn conn: WebsocketConnection,
  server_context server_context: ServerContext,
  session_id session_id: String,
  hostname _hostname: String,
) {
  ensure_atoms()
  topics.start()
  let Nil = effect_state.put_ws_state(conn, server_context, \"\")
  let Nil = effect_state.put_ws_session(session_id)
  topics.join(\"app\")
  topics.join(\"session:\" <> session_id)
  let selector = process.new_selector()
    |> process.select_other(fn(msg) { msg })
  #(Nil, Some(selector))
}

pub fn on_close(_state: Nil) -> Nil {
  Nil
}"
}

// -- Init (auth) --

fn generate_init_with_auth(
  auth_ref: String,
  from_session_ref: String,
) -> String {
  "pub fn on_init(
  conn conn: WebsocketConnection,
  server_context server_context: ServerContext,
  session_id session_id: String,
  hostname hostname: String,
) {
  ensure_atoms()
  topics.start()
  let Nil = effect_state.put_ws_session(session_id)
  case " <> auth_ref <> ".resolve(server_context, session_id) {
    Error(Nil) -> {
      // Infrastructure failure — no identity stored. Connection starts with
      // the un-enriched server_context. Subsequent page-init and RPC will see
      // get_ws_identity() -> Error(Nil) and fail closed for Required pages.
      let Nil = effect_state.put_ws_state(conn, server_context, \"\")
      topics.join(\"app\")
      topics.join(\"session:\" <> session_id)
      let selector = process.new_selector()
        |> process.select_other(fn(msg) { msg })
      #(Nil, Some(selector))
    }
    Ok(identity) -> {
      let #(_, enriched_sc) = " <> from_session_ref <> ".from_session(server_context: server_context, session_id: session_id, hostname: hostname, identity: identity)
      let Nil = effect_state.put_ws_state(conn, enriched_sc, \"\")
      let Nil = effect_state.put_ws_identity(identity)
      let Nil = effect_state.put_ws_hostname(hostname)
      let epoch = timestamp.from_unix_seconds(0)
      let now = duration.to_milliseconds(timestamp.difference(epoch, timestamp.system_time()))
      let Nil = effect_state.put_ws_auth_timestamp(now)
      topics.join(\"app\")
      topics.join(\"session:\" <> session_id)
      let selector = process.new_selector()
        |> process.select_other(fn(msg) { msg })
      #(Nil, Some(selector))
    }
  }
}

pub fn on_close(_state: Nil) -> Nil {
  Nil
}"
}

// -- Frame handler (no auth) --

fn generate_frame_handler_no_auth(
  page_contracts: List(#(ScannedRoute, PageContract)),
  protocol: String,
  has_client_context: Bool,
) -> String {
  let page_effects = page_effect_helpers(page_contracts, protocol)
  let json_fallback = json_non_rpc_text_fallback(has_client_context)
  let rpc_branch = "\n    _ -> {
      case wire.decode_ws_rpc_envelope(msg) {
        Ok(envelope) -> {
          let request_id = wire.rpc_request_id(envelope)
          debug_log(\"[rally:ws] RPC: request_id=\" <> int.to_string(request_id))
          case effect_state.get_stored_server_context() {
            Error(Nil) -> {
              io.println_error(\"[rally:ws] missing server_context; dropping RPC \" <> int.to_string(request_id))
              let result = wire.error_result(request_id, \"server_unavailable\")
              wire.send_rpc_result(conn, result)
              send_pending_frames(conn)
              mist.continue(state)
            }
            Ok(server_context) -> {
              let current_page = effect_state.get_ws_page()
              let start = timestamp.system_time()
              let #(result, new_ctx) = wire.dispatch_rpc(envelope, server_context)
              let elapsed_ms =
                timestamp.difference(start, timestamp.system_time())
                |> duration.to_milliseconds()

              let session_id = effect_state.get_ws_session()
              case system_db.get_conn() {
                Ok(db_conn) ->
                  system_db.log_to_server(
                    db: db_conn,
                    session_id: session_id,
                    user_id: Error(Nil),
                    page: current_page,
                    variant_name: wire.rpc_identity(envelope),
                    raw_payload: wire.rpc_raw_payload(envelope),
                    elapsed_ms: elapsed_ms,
                  )
                Error(Nil) -> {
                  io.println_error(\"[rally:ws] system_db unavailable; skipping log_to_server\")
                  Nil
                }
              }

              let Nil = effect_state.put_ws_state(conn, new_ctx, current_page)
              wire.send_rpc_result(conn, result)
              send_pending_frames(conn)
              mist.continue(state)
            }
          }
        }
        Error(Nil) -> " <> json_fallback <> "
      }
    }"

  let binary_branch = case protocol {
    "json" ->
      "\n    mist.Binary(_data) -> {
      let error_frame = wire.encode_error(None, [JsonError(\"frame\", \"binary frames are not supported by the JSON protocol\")])
      let _send_result = mist.send_text_frame(conn, error_frame)
      mist.continue(state)
    }"
    _ ->
      "\n    mist.Binary(data) -> {
      debug_log(\"[rally:ws] Binary frame: \" <> int.to_string(bit_array.byte_size(data)) <> \" bytes\")
      case wire.decode_ws_rpc_envelope(msg) {
        Ok(envelope) -> {
          let request_id = wire.rpc_request_id(envelope)
          debug_log(\"[rally:ws] RPC: request_id=\" <> int.to_string(request_id))
          case effect_state.get_stored_server_context() {
            Error(Nil) -> {
              io.println_error(\"[rally:ws] missing server_context; dropping RPC \" <> int.to_string(request_id))
              let result = wire.error_result(request_id, \"server_unavailable\")
              wire.send_rpc_result(conn, result)
              send_pending_frames(conn)
              mist.continue(state)
            }
            Ok(server_context) -> {
              let current_page = effect_state.get_ws_page()
              let start = timestamp.system_time()
              let #(result, new_ctx) = wire.dispatch_rpc(envelope, server_context)
              let elapsed_ms =
                timestamp.difference(start, timestamp.system_time())
                |> duration.to_milliseconds()

              let session_id = effect_state.get_ws_session()
              case system_db.get_conn() {
                Ok(db_conn) ->
                  system_db.log_to_server(
                    db: db_conn,
                    session_id: session_id,
                    user_id: Error(Nil),
                    page: current_page,
                    variant_name: wire.rpc_identity(envelope),
                    raw_payload: wire.rpc_raw_payload(envelope),
                    elapsed_ms: elapsed_ms,
                  )
                Error(Nil) -> {
                  io.println_error(\"[rally:ws] system_db unavailable; skipping log_to_server\")
                  Nil
                }
              }

              let Nil = effect_state.put_ws_state(conn, new_ctx, current_page)
              wire.send_rpc_result(conn, result)
              send_pending_frames(conn)
              mist.continue(state)
            }
          }
        }
        Error(Nil) ->
          case wire.decode_request(data) {
            Ok(#(page, request_id, value)) if request_id == 0 -> {
              debug_log(\"[rally:ws] page_init: \" <> page)
              let old_page = effect_state.get_ws_page()
              case effect_state.get_stored_server_context() {
                Error(Nil) -> {
                  io.println_error(\"[rally:ws] missing server_context; failing page_init for \" <> page)
                  let response_frame = wire.encode_response(request_id:, value: Error(\"server_unavailable\"))
                  let _send_result = mist.send_binary_frame(conn, response_frame)
                  send_pending_frames(conn)
                  mist.continue(state)
                }
                Ok(server_context) -> {
                  let Nil = effect_state.put_ws_state(conn, server_context, page)
                  let Nil = run_server_init(page, value, server_context)
                  case old_page {
                    \"\" -> Nil
                    _ -> topics.leave(\"page:\" <> old_page)
                  }
                  topics.join(\"page:\" <> page)
                  let response_frame = wire.encode_response(request_id:, value: wire.page_init_ok())
                  let _send_result = mist.send_binary_frame(conn, response_frame)
                  send_pending_frames(conn)
                  mist.continue(state)
                }
              }
            }
            Ok(#(page, request_id, value)) -> {
              debug_log(\"[rally:ws] page_update: \" <> page)
              case effect_state.get_stored_server_context() {
                Error(Nil) -> {
                  io.println_error(\"[rally:ws] missing server_context; dropping page_update for \" <> page)
                  let result = wire.error_result(request_id, \"server_unavailable\")
                  wire.send_rpc_result(conn, result)
                  send_pending_frames(conn)
                  mist.continue(state)
                }
                Ok(server_context) -> {
                  let current_page = effect_state.get_ws_page()
                  case current_page != page {
                    True -> {
                      let result = wire.error_result(request_id, \"Page mismatch\")
                      wire.send_rpc_result(conn, result)
                      send_pending_frames(conn)
                      mist.continue(state)
                    }
                    False -> {
                      case run_server_update(page, value, server_context) {
                        True -> {
                          let response_frame = wire.encode_response(request_id:, value: wire.page_init_ok())
                          let _send_result = mist.send_binary_frame(conn, response_frame)
                          send_pending_frames(conn)
                          mist.continue(state)
                        }
                        False -> {
                          let result = wire.error_result(request_id, \"Unknown page message\")
                          wire.send_rpc_result(conn, result)
                          send_pending_frames(conn)
                          mist.continue(state)
                        }
                      }
                    }
                  }
                }
              }
            }
            _ -> {
              debug_log(\"[rally:ws] decode_request FAILED\")
              mist.continue(state)
            }
          }
      }
    }"
  }

  let text_branch = case protocol {
    "json" ->
      string.replace(rpc_branch, "\n    _ ->", "\n    mist.Text(_data) ->")
    _ -> ""
  }

  let send_fn = case protocol {
    "json" -> "send_text_frame"
    _ -> "send_binary_frame"
  }

  let msg_catch_all = case protocol {
    "json" -> ""
    _ -> "\n    _ -> mist.continue(state)"
  }

  "pub fn handler(
  state state: Nil,
  msg msg: WebsocketMessage(a),
  conn conn: WebsocketConnection,
) {
  debug_log(\"[rally:ws] handler called\")
  case msg {" <> binary_branch <> text_branch <> "
    mist.Custom(msg) -> {
      case effect_state.decode_rally_push" <> case protocol {
    "json" -> "_json"
    _ -> ""
  } <> "(msg) {
        Ok(frame) -> {
          let _send_result = mist." <> send_fn <> "(conn, frame)
          mist.continue(state)
        }
        Error(Nil) -> mist.continue(state)
      }
    }
    mist.Closed -> mist.stop()
    mist.Shutdown -> mist.stop()" <> msg_catch_all <> "
  }
}

" <> helpers_string(protocol) <> page_effects
}

// -- Frame handler (auth) --

fn generate_frame_handler_with_auth(
  page_contracts: List(#(ScannedRoute, PageContract)),
  auth_ref: String,
  from_session_ref: String,
  endpoints: List(HandlerEndpoint),
  protocol: String,
  has_client_context: Bool,
) -> String {
  let has_endpoints = !list.is_empty(endpoints)
  let page_effects = page_effect_helpers(page_contracts, protocol)
  let page_auth_policy_fn = generate_page_auth_policy(page_contracts)
  let handler_page_info_fn = case has_endpoints {
    True -> generate_handler_page_info(page_contracts, endpoints, protocol)
    False -> ""
  }
  let check_page_authorize_fn =
    generate_ws_check_page_authorize(page_contracts, auth_ref)

  let binary_branch = case protocol {
    "json" ->
      "\n    mist.Binary(_data) -> {
      let error_frame = wire.encode_error(None, [JsonError(\"frame\", \"binary frames are not supported by the JSON protocol\")])
      let _send_result = mist.send_text_frame(conn, error_frame)
      mist.continue(state)
    }"
    _ -> "\n    mist.Binary(data) -> {
      debug_log(\"[rally:ws] Binary frame: \" <> int.to_string(bit_array.byte_size(data)) <> \" bytes\")
      // Reauth: re-resolve identity if the last auth check is stale.
      let epoch = timestamp.from_unix_seconds(0)
      let now = duration.to_milliseconds(timestamp.difference(epoch, timestamp.system_time()))
      let last_auth = effect_state.get_ws_auth_timestamp()
      case now - last_auth > 1800000 {
        True -> {
          let session_id = effect_state.get_ws_session()
          let hostname = effect_state.get_ws_hostname()
          let current_page = effect_state.get_ws_page()
          case effect_state.get_stored_server_context() {
            Error(Nil) -> {
              io.println_error(\"[rally:ws] missing server_context during reauth; skipping reauth\")
              Nil
            }
            Ok(server_context) -> {
              case " <> auth_ref <> ".resolve(server_context, session_id) {
                Error(Nil) -> {
                  effect_state.clear_ws_auth_state()
                  let Nil = effect_state.put_ws_state(conn, server_context, current_page)
                  Nil
                }
                Ok(identity) -> {
                  let #(_, enriched_sc) = " <> from_session_ref <> ".from_session(server_context: server_context, session_id: session_id, hostname: hostname, identity: identity)
                  let Nil = effect_state.put_ws_state(conn, enriched_sc, current_page)
                  let Nil = effect_state.put_ws_identity(identity)
                  let Nil = effect_state.put_ws_auth_timestamp(now)
                  Nil
                }
              }
            }
          }
        }
        False -> Nil
      }
      case wire.decode_ws_rpc_envelope(msg) {
" <> rpc_body(has_endpoints, auth_ref) <> "
        Error(Nil) ->
          case wire.decode_request(data) {
            Ok(#(page, request_id, value)) if request_id == 0 -> {
              debug_log(\"[rally:ws] page_init: \" <> page)
              case effect_state.get_stored_server_context() {
                Error(Nil) -> {
                  io.println_error(\"[rally:ws] missing server_context; failing page_init for \" <> page)
                  let response_frame = wire.encode_response(request_id:, value: Error(\"server_unavailable\"))
                  let _send_result = mist.send_binary_frame(conn, response_frame)
                  send_pending_frames(conn)
                  mist.continue(state)
                }
                Ok(server_context) -> {
                  let #(can_proceed, response_frame) = case check_page_access(page, server_context) {
                    Ok(Nil) -> #(True, wire.encode_response(request_id:, value: wire.page_init_ok()))
                    Error(message) -> #(False, wire.encode_response(request_id:, value: Error(message)))
                  }
                  case can_proceed {
                    True -> {
                      let old_page = effect_state.get_ws_page()
                      let Nil = effect_state.put_ws_state(conn, server_context, page)
                      let Nil = run_server_init(page, value, server_context)
                      case old_page {
                        \"\" -> Nil
                        _ -> topics.leave(\"page:\" <> old_page)
                      }
                      topics.join(\"page:\" <> page)
                      let _send_result = mist.send_binary_frame(conn, response_frame)
                      send_pending_frames(conn)
                      mist.continue(state)
                    }
                    False -> {
                      let _send_result = mist.send_binary_frame(conn, response_frame)
                      send_pending_frames(conn)
                      mist.continue(state)
                    }
                  }
                }
              }
            }
            Ok(#(page, request_id, value)) -> {
              debug_log(\"[rally:ws] page_update: \" <> page)
              case effect_state.get_stored_server_context() {
                Error(Nil) -> {
                  io.println_error(\"[rally:ws] missing server_context; dropping page_update for \" <> page)
                  let result = wire.auth_error_result(request_id, \"server_unavailable\")
                  wire.send_rpc_result(conn, result)
                  send_pending_frames(conn)
                  mist.continue(state)
                }
                Ok(server_context) -> {
                  let current_page = effect_state.get_ws_page()
                  case current_page != page {
                    True -> {
                      let result = wire.auth_error_result(request_id, \"auth:page_mismatch\")
                      wire.send_rpc_result(conn, result)
                      send_pending_frames(conn)
                      mist.continue(state)
                    }
                    False -> {
                      case check_page_access(page, server_context) {
                        Error(message) -> {
                          let result = wire.auth_error_result(request_id, message)
                          wire.send_rpc_result(conn, result)
                          send_pending_frames(conn)
                          mist.continue(state)
                        }
                        Ok(Nil) -> {
                          case run_server_update(page, value, server_context) {
                            True -> {
                              let response_frame = wire.encode_response(request_id:, value: wire.page_init_ok())
                              let _send_result = mist.send_binary_frame(conn, response_frame)
                              send_pending_frames(conn)
                              mist.continue(state)
                            }
                            False -> {
                              let result = wire.error_result(request_id, \"Unknown page message\")
                              wire.send_rpc_result(conn, result)
                              send_pending_frames(conn)
                              mist.continue(state)
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            _ -> {
              debug_log(\"[rally:ws] decode_request FAILED\")
              mist.continue(state)
            }
          }
      }
    }"
  }

  let json_fallback = json_non_rpc_text_fallback(has_client_context)
  let text_branch = case protocol {
    "json" -> "\n    mist.Text(_data) -> {
      // Reauth: re-resolve identity if the last auth check is stale.
      let epoch = timestamp.from_unix_seconds(0)
      let now = duration.to_milliseconds(timestamp.difference(epoch, timestamp.system_time()))
      let last_auth = effect_state.get_ws_auth_timestamp()
      case now - last_auth > 1800000 {
        True -> {
          let session_id = effect_state.get_ws_session()
          let hostname = effect_state.get_ws_hostname()
          let current_page = effect_state.get_ws_page()
          case effect_state.get_stored_server_context() {
            Error(Nil) -> {
              io.println_error(\"[rally:ws] missing server_context during reauth; skipping reauth\")
              Nil
            }
            Ok(server_context) -> {
              case " <> auth_ref <> ".resolve(server_context, session_id) {
                Error(Nil) -> {
                  effect_state.clear_ws_auth_state()
                  let Nil = effect_state.put_ws_state(conn, server_context, current_page)
                  Nil
                }
                Ok(identity) -> {
                  let #(_, enriched_sc) = " <> from_session_ref <> ".from_session(server_context: server_context, session_id: session_id, hostname: hostname, identity: identity)
                  let Nil = effect_state.put_ws_state(conn, enriched_sc, current_page)
                  let Nil = effect_state.put_ws_identity(identity)
                  let Nil = effect_state.put_ws_auth_timestamp(now)
                  Nil
                }
              }
            }
          }
        }
        False -> Nil
      }
      case wire.decode_ws_rpc_envelope(msg) {
" <> rpc_body(has_endpoints, auth_ref) <> "
        Error(Nil) -> " <> json_fallback <> "
      }
    }"
    _ -> ""
  }

  let send_fn = case protocol {
    "json" -> "send_text_frame"
    _ -> "send_binary_frame"
  }

  let msg_catch_all = case protocol {
    "json" -> ""
    _ -> "\n    _ -> mist.continue(state)"
  }

  let handler = "pub fn handler(
  state state: Nil,
  msg msg: WebsocketMessage(a),
  conn conn: WebsocketConnection,
) {
  debug_log(\"[rally:ws] handler called\")
  case msg {" <> binary_branch <> text_branch <> "
    mist.Custom(msg) -> {
      case effect_state.decode_rally_push" <> case protocol {
      "json" -> "_json"
      _ -> ""
    } <> "(msg) {
        Ok(frame) -> {
          let _send_result = mist." <> send_fn <> "(conn, frame)
          mist.continue(state)
        }
        Error(Nil) -> mist.continue(state)
      }
    }
    mist.Closed -> mist.stop()
    mist.Shutdown -> mist.stop()" <> msg_catch_all <> "
  }
}

" <> helpers_string(protocol)

  let page_info_section = case has_endpoints {
    True -> "\n\n" <> handler_page_info_fn
    False -> ""
  }

  handler
  <> "\n\n"
  <> page_auth_policy_fn
  <> "\n\n"
  <> page_has_authorize_fn(page_contracts)
  <> page_info_section
  <> "\n\n"
  <> check_page_authorize_fn
  <> "\n\n"
  <> page_access_check_fn(auth_ref)
  <> page_effects
}

fn rpc_body(has_endpoints: Bool, auth_ref: String) -> String {
  case has_endpoints {
    True ->
      "            Ok(envelope) -> {\n"
      <> "          let request_id = wire.rpc_request_id(envelope)\n"
      <> "          debug_log(\"[rally:ws] RPC: request_id=\" <> int.to_string(request_id))\n"
      <> "          case effect_state.get_stored_server_context() {\n"
      <> "            Error(Nil) -> {\n"
      <> "              io.println_error(\"[rally:ws] missing server_context; dropping RPC \" <> int.to_string(request_id))\n"
      <> "              let result = wire.error_result(request_id, \"server_unavailable\")\n"
      <> "              wire.send_rpc_result(conn, result)\n"
      <> "              send_pending_frames(conn)\n"
      <> "              mist.continue(state)\n"
      <> "            }\n"
      <> "            Ok(server_context) -> {\n"
      <> "          let current_page = effect_state.get_ws_page()\n"
      <> "          case effect_state.get_ws_identity() {\n"
      <> "            Error(Nil) -> {\n"
      <> "              let result = wire.auth_error_result(request_id, \"auth:forbidden\")\n"
      <> "              wire.send_rpc_result(conn, result)\n"
      <> "              send_pending_frames(conn)\n"
      <> "              mist.continue(state)\n"
      <> "            }\n"
      <> "            Ok(identity) -> {\n"
      <> "              case handler_page_info(wire.rpc_identity(envelope)) {\n"
      <> "                    Error(Nil) -> {\n"
      <> "                      let result = wire.auth_error_result(request_id, \"auth:unknown_rpc\")\n"
      <> "                      wire.send_rpc_result(conn, result)\n"
      <> "                      send_pending_frames(conn)\n"
      <> "                      mist.continue(state)\n"
      <> "                    }\n"
      <> "                    Ok(info) -> {\n"
      <> "                      let owning_page = info.page\n"
      <> "                      let required = info.required\n"
      <> "                      let has_authorize = info.has_authorize\n"
      <> "                      case owning_page != current_page {\n"
      <> "                        True -> {\n"
      <> "                          let result = wire.auth_error_result(request_id, \"auth:page_mismatch\")\n"
      <> "                          wire.send_rpc_result(conn, result)\n"
      <> "                          send_pending_frames(conn)\n"
      <> "                          mist.continue(state)\n"
      <> "                        }\n"
      <> "                        False -> {\n"
      <> "                          case required && !"
      <> auth_ref
      <> ".is_authenticated(identity) {\n"
      <> "                        True -> {\n"
      <> "                          let result = wire.auth_error_result(request_id, \"auth:redirect:\" <> "
      <> auth_ref
      <> ".redirect_url)\n"
      <> "                          wire.send_rpc_result(conn, result)\n"
      <> "                          send_pending_frames(conn)\n"
      <> "                          mist.continue(state)\n"
      <> "                        }\n"
      <> "                        False -> {\n"
      <> "                          case has_authorize && !check_page_authorize(owning_page, server_context, identity) {\n"
      <> "                            True -> {\n"
      <> "                              let result = wire.auth_error_result(request_id, \"auth:forbidden\")\n"
      <> "                              wire.send_rpc_result(conn, result)\n"
      <> "                              send_pending_frames(conn)\n"
      <> "                              mist.continue(state)\n"
      <> "                            }\n"
      <> "                            False -> {\n"
      <> "                              let start = timestamp.system_time()\n"
      <> "                              let #(result, new_ctx) = wire.dispatch_rpc(envelope, server_context, identity)\n"
      <> "                              let elapsed_ms =\n"
      <> "                                timestamp.difference(start, timestamp.system_time())\n"
      <> "                                |> duration.to_milliseconds()\n"
      <> "\n"
      <> "                              let session_id = effect_state.get_ws_session()\n"
      <> "                              case system_db.get_conn() {\n"
      <> "                                Ok(db_conn) -> system_db.log_to_server(db: db_conn, session_id: session_id, user_id: Error(Nil), page: current_page, variant_name: wire.rpc_identity(envelope), raw_payload: wire.rpc_raw_payload(envelope), elapsed_ms: elapsed_ms)\n"
      <> "                                Error(Nil) -> {\n"
      <> "                                  io.println_error(\"[rally:ws] system_db unavailable; skipping log_to_server\")\n"
      <> "                                  Nil\n"
      <> "                                }\n"
      <> "                              }\n"
      <> "\n"
      <> "                              let Nil = effect_state.put_ws_state(conn, new_ctx, current_page)\n"
      <> "                              wire.send_rpc_result(conn, result)\n"
      <> "                              send_pending_frames(conn)\n"
      <> "                              mist.continue(state)\n"
      <> "                            }\n"
      <> "                          }\n"
      <> "                        }\n"
      <> "                      }\n"
      <> "                        }\n"
      <> "                      }\n"
      <> "                    }\n"
      <> "              }\n"
      <> "            }\n"
      <> "          }\n"
      <> "            }\n"
      <> "          }\n"
      <> "        }"
    False ->
      "            Ok(envelope) -> {
          let request_id = wire.rpc_request_id(envelope)
          debug_log(\"[rally:ws] RPC: request_id=\" <> int.to_string(request_id))
          let result = wire.auth_error_result(request_id, \"auth:unknown_rpc\")
          wire.send_rpc_result(conn, result)
          send_pending_frames(conn)
          mist.continue(state)
        }"
  }
}

fn json_non_rpc_text_fallback(has_client_context: Bool) -> String {
  case has_client_context {
    True ->
      "{
          case wire.decode_request(data) {
            Ok(envelope) if envelope.module == \"__ClientContext__\" -> {
              case wire.decode_client_context_msg(envelope.message) {
                Ok(client_context_msg) -> {
                  let push_frame = wire.encode_push(\"__ClientContext__\", client_context_msg)
                  let _push_result = mist.send_text_frame(conn, push_frame)
                  let response_frame = wire.encode_response(request_id: envelope.request_id, value: wire.page_init_ok())
                  let _response_result = mist.send_text_frame(conn, response_frame)
                  send_pending_frames(conn)
                  mist.continue(state)
                }
                Error(errors) -> {
                  let error_frame = wire.encode_error(Some(envelope.request_id), errors)
                  let _send_result = mist.send_text_frame(conn, error_frame)
                  send_pending_frames(conn)
                  mist.continue(state)
                }
              }
            }
            _ -> {
              let result = wire.malformed_rpc_result()
              wire.send_rpc_result(conn, result)
              send_pending_frames(conn)
              mist.continue(state)
            }
          }
        }"
    False ->
      "{
          let result = wire.malformed_rpc_result()
          wire.send_rpc_result(conn, result)
          send_pending_frames(conn)
          mist.continue(state)
        }"
  }
}

fn generate_page_auth_policy(
  page_contracts: List(#(ScannedRoute, PageContract)),
) -> String {
  let arms =
    list.filter_map(page_contracts, fn(pair) {
      let #(route, contract) = pair
      case contract.has_page_auth {
        True -> {
          let policy = case contract.page_auth_required {
            True -> "rally_auth.Required"
            False -> "rally_auth.Optional"
          }
          Ok("    \"" <> route.variant_name <> "\" -> " <> policy)
        }
        False -> Error(Nil)
      }
    })
    |> string.join("\n")
    |> fn(s) { s <> "\n    _ -> rally_auth.Optional" }

  "import rally/runtime/auth as rally_auth

fn page_auth_policy(page: String) -> rally_auth.AuthPolicy {
  case page {
" <> arms <> "
  }
}"
}

fn page_has_authorize_fn(
  page_contracts: List(#(ScannedRoute, PageContract)),
) -> String {
  let arms =
    list.filter_map(page_contracts, fn(pair) {
      let #(route, contract) = pair
      case contract.has_authorize {
        True -> Ok("    \"" <> route.variant_name <> "\" -> True")
        False -> Error(Nil)
      }
    })
    |> string.join("\n")
    |> fn(s) {
      case s {
        "" -> "    _ -> False"
        _ -> s <> "\n    _ -> False"
      }
    }

  "fn page_has_authorize(page: String) -> Bool {
  case page {
" <> arms <> "
  }
}"
}

fn generate_ws_check_page_authorize(
  page_contracts: List(#(ScannedRoute, PageContract)),
  auth_ref: String,
) -> String {
  let with_auth =
    list.filter_map(page_contracts, fn(pair) {
      let #(route, contract) = pair
      case contract.has_authorize {
        True ->
          Ok(#(
            route.variant_name,
            route.module_path,
            module_to_alias(route.module_path),
          ))
        False -> Error(Nil)
      }
    })
  case with_auth {
    [] -> stub_check_page_authorize(auth_ref)
    _ -> {
      let arms =
        list.map(with_auth, fn(pair) {
          let #(page, _, alias) = pair
          "    \""
          <> page
          <> "\" -> "
          <> alias
          <> ".authorize(server_context, identity)"
        })
        |> string.join("\n")
        |> fn(s) { s <> "\n    _ -> False" }

      let imports =
        list.map(with_auth, fn(pair) {
          let #(_, module_path, alias) = pair
          import_as(module_path, alias)
        })
        |> list.unique
        |> string.join("\n")

      imports
      <> "\n\nfn check_page_authorize(page: String, server_context: ServerContext, identity: "
      <> auth_ref
      <> ".Identity) -> Bool {
  case page {
"
      <> arms
      <> "
  }
}"
    }
  }
}

fn generate_handler_page_info(
  page_contracts: List(#(ScannedRoute, PageContract)),
  endpoints: List(HandlerEndpoint),
  protocol: String,
) -> String {
  // Build a dict from page module path to route identity and contract for quick lookup.
  let contract_for =
    list.filter_map(page_contracts, fn(pair) {
      let #(route, contract) = pair
      Ok(#(route.module_path, route.variant_name, contract))
    })

  let arms =
    list.flat_map(endpoints, fn(endpoint) {
      case
        list.find_map(contract_for, fn(pair) {
          let #(module_path, variant_name, contract) = pair
          case module_path == endpoint.module_path {
            True -> Ok(#(variant_name, contract))
            False -> Error(Nil)
          }
        })
      {
        Ok(page_info) -> {
          let #(variant_name, contract) = page_info
          endpoint_wire_tags(endpoint, protocol)
          |> list.map(fn(wire_tag) {
            "    \""
            <> wire_tag
            <> "\" -> Ok(PageAuthInfo(page: \""
            <> variant_name
            <> "\", required: "
            <> bool_str(contract.page_auth_required)
            <> ", has_authorize: "
            <> bool_str(contract.has_authorize)
            <> "))"
          })
        }
        Error(Nil) -> []
      }
    })
    |> string.join("\n")
    |> fn(s) { s <> "\n    _ -> Error(Nil)" }

  "type PageAuthInfo {
  PageAuthInfo(page: String, required: Bool, has_authorize: Bool)
}

fn handler_page_info(variant: String) -> Result(PageAuthInfo, Nil) {
  case variant {
" <> arms <> "
  }
}"
}

fn page_effect_helpers(
  page_contracts: List(#(ScannedRoute, PageContract)),
  protocol: String,
) -> String {
  let pages = stateful_pages(page_contracts)
  case protocol, pages {
    "json", _ -> ""
    _, [] -> page_effect_stubs()
    _, _ -> {
      let init_arms =
        pages
        |> list.filter_map(fn(page) {
          let #(route, contract, alias) = page
          case has_server_init(contract) {
            True ->
              Ok(
                "    \""
                <> route.variant_name
                <> "\" -> {\n"
                <> server_init_param_bindings(route)
                <> "      let #(server_model, server_effect) = "
                <> alias
                <> ".server_init("
                <> server_init_args(route)
                <> ")\n"
                <> "      let Nil = effect_state.put_ws_server_model(server_model)\n"
                <> "      effect_runner.perform(server_effect)\n"
                <> "    }",
              )
            False -> Error(Nil)
          }
        })
        |> string.join("\n")
        |> fn(s) {
          case s {
            "" -> "    _ -> Nil"
            _ -> s <> "\n    _ -> Nil"
          }
        }

      let update_arms =
        pages
        |> list.filter_map(fn(page) {
          let #(route, contract, alias) = page
          case has_server_update(contract) {
            True ->
              Ok(
                "    \""
                <> route.variant_name
                <> "\" -> {\n"
                <> "      case effect_state.get_ws_server_model() {\n"
                <> "        Error(Nil) -> False\n"
                <> "        Ok(server_model) -> {\n"
                <> "          let msg = wire.coerce(value)\n"
                <> "          let #(new_server_model, server_effect) = "
                <> alias
                <> ".server_update(server_model, msg, server_context)\n"
                <> "          let Nil = effect_state.put_ws_server_model(new_server_model)\n"
                <> "          effect_runner.perform(server_effect)\n"
                <> "          True\n"
                <> "        }\n"
                <> "      }\n"
                <> "    }",
              )
            False -> Error(Nil)
          }
        })
        |> string.join("\n")
        |> fn(s) {
          case s {
            "" -> "    _ -> False"
            _ -> s <> "\n    _ -> False"
          }
        }

      "\n\nfn run_server_init(page: String, value: dynamic.Dynamic, server_context: ServerContext) -> Nil {\n"
      <> "  case page {\n"
      <> init_arms
      <> "\n  }\n}"
      <> "\n\nfn run_server_update(page: String, value: dynamic.Dynamic, server_context: ServerContext) -> Bool {\n"
      <> "  case page {\n"
      <> update_arms
      <> "\n  }\n}"
    }
  }
}

fn page_effect_stubs() -> String {
  "\n\nfn run_server_init(_page: String, _value: a, _server_context: ServerContext) -> Nil {
  Nil
}

fn run_server_update(_page: String, _value: a, _server_context: ServerContext) -> Bool {
  False
}"
}

fn stateful_pages(
  page_contracts: List(#(ScannedRoute, PageContract)),
) -> List(#(ScannedRoute, PageContract, String)) {
  page_contracts
  |> list.filter_map(fn(pair) {
    let #(route, contract) = pair
    case has_server_init(contract) || has_server_update(contract) {
      True -> Ok(#(route, contract, module_to_alias(route.module_path)))
      False -> Error(Nil)
    }
  })
}

fn has_server_init(contract: PageContract) -> Bool {
  contract.has_server_init
}

fn has_server_update(contract: PageContract) -> Bool {
  contract.has_server_update
}

fn server_init_param_bindings(route: ScannedRoute) -> String {
  route.params
  |> list.index_map(fn(_param, index) {
    let expr = case route.params {
      [_] -> "wire.coerce(value)"
      _ ->
        "wire.coerce(wire.tuple_element(value, " <> int.to_string(index) <> "))"
    }
    "      let param_" <> int.to_string(index) <> " = " <> expr <> "\n"
  })
  |> string.join("")
}

fn server_init_args(route: ScannedRoute) -> String {
  case route.params {
    [] -> "server_context"
    params -> {
      let param_args =
        params
        |> list.index_map(fn(_, index) { "param_" <> int.to_string(index) })
        |> string.join(", ")
      "server_context, " <> param_args
    }
  }
}

fn endpoint_wire_tags(
  endpoint: HandlerEndpoint,
  protocol: String,
) -> List(String) {
  case protocol {
    "json" -> [json_rpc_dispatch.endpoint_json_tag(endpoint)]
    _ -> {
      let function_tag = "server_" <> endpoint.fn_name
      let hash_tags = case endpoint.msg_type {
        Some(#(module_path, type_name)) -> {
          let fields = list.map(endpoint.params, fn(param) { param.1 })
          let #(_, hash) =
            wire_identity.wire_identity(module_path, type_name, fields)
          [hash]
        }
        None -> []
      }
      list.append([function_tag], hash_tags)
    }
  }
}

fn stub_check_page_authorize(auth_ref: String) -> String {
  "fn check_page_authorize(page: String, _server_context: ServerContext, _identity: "
  <> auth_ref
  <> ".Identity) -> Bool {
  case page {
    _ -> False
  }
}"
}

fn page_access_check_fn(auth_ref: String) -> String {
  "fn check_page_access(page: String, server_context: ServerContext) -> Result(Nil, String) {
  case page_auth_policy(page) {
    rally_auth.Required -> {
      case effect_state.get_ws_identity() {
        Error(Nil) -> Error(\"auth:redirect:\" <> "
  <> auth_ref
  <> ".redirect_url)
        Ok(identity) -> {
          case "
  <> auth_ref
  <> ".is_authenticated(identity) {
            False -> Error(\"auth:redirect:\" <> "
  <> auth_ref
  <> ".redirect_url)
            True -> {
              case page_has_authorize(page) && !check_page_authorize(page, server_context, identity) {
                True -> Error(\"auth:forbidden\")
                False -> Ok(Nil)
              }
            }
          }
        }
      }
    }
    rally_auth.Optional -> {
      case page_has_authorize(page) {
        False -> Ok(Nil)
        True -> {
          case effect_state.get_ws_identity() {
            Error(Nil) -> Error(\"auth:forbidden\")
            Ok(identity) -> {
              case check_page_authorize(page, server_context, identity) {
                False -> Error(\"auth:forbidden\")
                True -> Ok(Nil)
              }
            }
          }
        }
      }
    }
  }
}"
}

// -- Generated helper functions (embedded in output) --

fn helpers_string(protocol: String) -> String {
  let send_fn = case protocol {
    "json" -> "send_text_frame"
    _ -> "send_binary_frame"
  }
  "
fn send_pending_frames(conn: WebsocketConnection) -> Nil {
  let frames = effect_state.drain_outgoing_frames()
  list.each(frames, fn(frame) {
    let _send_result = mist." <> send_fn <> "(conn, frame)
    Nil
  })
}

fn debug_log(message: String) -> Nil {
  use <- bool.guard(when: !env.is_dev(), return: Nil)
  io.println_error(message)
}"
}

// -- Shared string helpers --

fn last_segment(module_path: String) -> String {
  case string.split(module_path, "/") |> list.last {
    Ok(seg) -> seg
    Error(Nil) -> module_path
  }
}

fn module_to_alias(module_path: String) -> String {
  string.replace(module_path, "/", "_")
}

fn bool_str(b: Bool) -> String {
  bool.to_string(b)
}

fn import_as(module_path: String, alias: String) -> String {
  case last_segment(module_path) == alias {
    True -> "import " <> module_path
    False -> "import " <> module_path <> " as " <> alias
  }
}
