%% Code generated by libero. DO NOT EDIT.
%%
%% Per-type wire-format encode/decode transformers. Translates between
%% BEAM-shape (bare atom constructor tags) and wire-shape (10-char
%% hex hash atom tags computed at codegen time by libero/wire_identity).
%%
%% encode_<T>/1 takes a BEAM tuple and returns the wire-shape tuple.
%% decode_<T>/1 is the inverse. Function names are qualified by
%% module path so types with the same name in different Gleam modules
%% do not collide in this Erlang module's function table.

-module(generated@public@rpc_wire).
-export([
    encode_public_pages_home___server_increment/1,
    decode_public_pages_home___server_increment/1,
    encode_public_pages_home___increment_result/1,
    decode_public_pages_home___increment_result/1,
    encode_public_pages_home___server_increment_by/1,
    decode_public_pages_home___server_increment_by/1,
    encode_public_pages_home___model/1,
    decode_public_pages_home___model/1,
    encode_public_pages_notifications___model/1,
    decode_public_pages_notifications___model/1,
    encode_public_pages_home___to_client/1,
    decode_public_pages_home___to_client/1,
    encode_public_pages_notifications___to_client/1,
    decode_public_pages_notifications___to_client/1,
    encode_term/1,
    decode_term/1,
    encode_float/1,
    decode_client_msg/1,
    encode_response_increment/1,
    encode_response_increment_by/1,
    encode_push/2
]).

%% Ensure whole-number floats stay floats on the wire. JS erases the
%% Int/Float distinction at runtime; this normalisation on the BEAM
%% side preserves wire-format type fidelity end-to-end.
encode_float(F) when is_float(F) -> F;
encode_float(N) when is_integer(N) -> N + 0.0.

%% Type: public/pages/home_.ServerIncrement
encode_public_pages_home___server_increment(server_increment) ->
    '3adf004bda'.

decode_public_pages_home___server_increment(Value) -> decode_public_pages_home___server_increment(Value, 0).

decode_public_pages_home___server_increment(_Value, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_public_pages_home___server_increment('3adf004bda', _Depth) ->
    server_increment.

%% Type: public/pages/home_.IncrementResult
encode_public_pages_home___increment_result({increment_result, F0, F1}) ->
    {'003511dd1c', F0, F1}.

decode_public_pages_home___increment_result(Value) -> decode_public_pages_home___increment_result(Value, 0).

decode_public_pages_home___increment_result(_Value, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_public_pages_home___increment_result({'003511dd1c', F0, F1}, _Depth) ->
    {increment_result, F0, F1}.

%% Type: public/pages/home_.ServerIncrementBy
encode_public_pages_home___server_increment_by({server_increment_by, F0}) ->
    {'10251ccd57', F0}.

decode_public_pages_home___server_increment_by(Value) -> decode_public_pages_home___server_increment_by(Value, 0).

decode_public_pages_home___server_increment_by(_Value, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_public_pages_home___server_increment_by({'10251ccd57', F0}, _Depth) ->
    {server_increment_by, F0}.

%% Type: public/pages/home_.Model
encode_public_pages_home___model({model, F0}) ->
    {'e4ff4f2689', F0}.

decode_public_pages_home___model(Value) -> decode_public_pages_home___model(Value, 0).

decode_public_pages_home___model(_Value, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_public_pages_home___model({'e4ff4f2689', F0}, _Depth) ->
    {model, F0}.

%% Type: public/pages/notifications_.Model
encode_public_pages_notifications___model({model, F0}) ->
    {'42a9f6fcde', F0}.

decode_public_pages_notifications___model(Value) -> decode_public_pages_notifications___model(Value, 0).

decode_public_pages_notifications___model(_Value, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_public_pages_notifications___model({'42a9f6fcde', F0}, _Depth) ->
    {model, F0}.

%% Type: public/pages/home_.ToClient
encode_public_pages_home___to_client({updated, F0}) ->
    {'19ae752434', F0}.

decode_public_pages_home___to_client(Value) -> decode_public_pages_home___to_client(Value, 0).

decode_public_pages_home___to_client(_Value, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_public_pages_home___to_client({'19ae752434', F0}, _Depth) ->
    {updated, F0}.

%% Type: public/pages/notifications_.ToClient
encode_public_pages_notifications___to_client({updated, F0}) ->
    {'45ac7f3cba', F0}.

decode_public_pages_notifications___to_client(Value) -> decode_public_pages_notifications___to_client(Value, 0).

decode_public_pages_notifications___to_client(_Value, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_public_pages_notifications___to_client({'45ac7f3cba', F0}, _Depth) ->
    {updated, F0}.

encode_term(Term) -> encode_term(Term, 0).

encode_term(_Term, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
encode_term(Tuple, Depth) when is_tuple(Tuple), tuple_size(Tuple) > 0 ->
    list_to_tuple([encode_term(E, Depth + 1) || E <- tuple_to_list(Tuple)]);
encode_term(List, Depth) when is_list(List) ->
    [encode_term(X, Depth + 1) || X <- List];
encode_term(Map, Depth) when is_map(Map) ->
    maps:map(fun(_K, V) -> encode_term(V, Depth + 1) end, Map);
encode_term(Other, _Depth) -> Other.

decode_term(Term) -> decode_term(Term, 0).

decode_term(_Term, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_term(Atom, _Depth) when is_atom(Atom) ->
    case Atom of
        '3adf004bda' -> server_increment;
        Other -> Other
    end;
decode_term(Tuple, Depth) when is_tuple(Tuple), tuple_size(Tuple) > 0 ->
    case {element(1, Tuple), tuple_size(Tuple)} of
        {'003511dd1c', 3} -> decode_public_pages_home___increment_result(Tuple, Depth + 1);
        {'10251ccd57', 2} -> decode_public_pages_home___server_increment_by(Tuple, Depth + 1);
        {'e4ff4f2689', 2} -> decode_public_pages_home___model(Tuple, Depth + 1);
        {'42a9f6fcde', 2} -> decode_public_pages_notifications___model(Tuple, Depth + 1);
        {'19ae752434', 2} -> decode_public_pages_home___to_client(Tuple, Depth + 1);
        {'45ac7f3cba', 2} -> decode_public_pages_notifications___to_client(Tuple, Depth + 1);
        _ -> list_to_tuple([decode_term(E, Depth + 1) || E <- tuple_to_list(Tuple)])
    end;
decode_term(List, Depth) when is_list(List) ->
    [decode_term(X, Depth + 1) || X <- List];
decode_term(Map, Depth) when is_map(Map) ->
    maps:map(fun(_K, V) -> decode_term(V, Depth + 1) end, Map);
decode_term(Other, _Depth) -> Other.

decode_client_msg(Msg) -> decode_client_msg(Msg, 0).

decode_client_msg(_Msg, Depth) when Depth >= 512 ->
    error({wire_depth_exceeded, Depth});
decode_client_msg('3adf004bda', _Depth) ->
    server_increment;
decode_client_msg(server_increment, _Depth) ->
    server_increment;
decode_client_msg({'10251ccd57', F0}, _Depth) ->
    {server_increment_by, F0};
decode_client_msg({server_increment_by, F0}, _Depth) ->
    {server_increment_by, F0};
decode_client_msg(Other, _Depth) ->
    Other.

encode_response_increment({ok, V}) ->
    {ok, V};
encode_response_increment({error, E}) ->
    {error, E}.

encode_response_increment_by({ok, V}) ->
    {ok, encode_public_pages_home___increment_result(V)};
encode_response_increment_by({error, E}) ->
    {error, E}.
encode_push(<<"Public">>, Msg) ->
    encode_public_pages_home___to_client(Msg);
encode_push(<<"PublicNotifications">>, Msg) ->
    encode_public_pages_notifications___to_client(Msg);
encode_push(Page, _Msg) ->
    error({no_push_encoder, Page}).
