////
//// Client-side effect shim. Provides the same API as
//// rally/runtime/effect but backed by the client transport.

import generated/transport
import generated/types

// Generated by Rally — do not edit.

import lustre/effect.{type Effect}

pub fn rpc(msg: a, on_response on_response: fn(b) -> msg) -> Effect(msg) {
  effect.from(fn(dispatch) {
    transport.send_rpc(
      types.json_encode_client_msg(transport.coerce(msg)),
      fn(response) { dispatch(on_response(transport.coerce(response))) },
    )
  })
}

pub fn send_to_client_context(_msg: a) -> Effect(b) {
  effect.from(fn(_dispatch) { Nil })
}

pub fn navigate(path: String) -> Effect(a) {
  effect.from(fn(_dispatch) {
    do_navigate(path)
    Nil
  })
}

@external(javascript, "./rally_effect_ffi.mjs", "navigate")
fn do_navigate(_path: String) -> Nil {
  Nil
}

pub fn none() -> Effect(a) {
  effect.none()
}

pub fn get_ws_session() -> String {
  ""
}

pub fn set_dark_mode(enabled: Bool) -> Effect(a) {
  effect.from(fn(_dispatch) {
    do_set_dark_mode(enabled)
    Nil
  })
}

@external(javascript, "./rally_effect_ffi.mjs", "setDarkMode")
fn do_set_dark_mode(_enabled: Bool) -> Nil {
  Nil
}

pub fn set_lang(lang: String) -> Effect(a) {
  effect.from(fn(_dispatch) {
    do_set_lang(lang)
    Nil
  })
}

@external(javascript, "./rally_effect_ffi.mjs", "setLang")
fn do_set_lang(_lang: String) -> Nil {
  Nil
}

@external(javascript, "./rally_effect_ffi.mjs", "readDarkModeCookie")
pub fn read_dark_mode() -> Bool {
  False
}

@external(javascript, "./rally_effect_ffi.mjs", "readLangCookie")
pub fn read_lang() -> String {
  ""
}
