//// Route type, parse function, path builder, and page dispatch codegen.
////
//// Generates router.gleam (Route type, parse_route, route_to_path, href),
//// page_dispatch.gleam (PageModel/PageMsg unions, per-route init/update/view),
//// protocol_wire.gleam facade, and RPC dispatch scaffolding.

import gleam/dict
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/order
import gleam/string
import libero/scanner.{type HandlerEndpoint}
import rally/internal/generator/json_rpc_dispatch
import rally/internal/generator/rpc_dispatch
import rally/internal/types.{
  type AuthConfig, type PageContract, type ScannedRoute, type UrlSegment,
  AuthConfig, DynamicSegment, IntParam, ScannedRoute, StaticSegment, StringParam,
}

/// Generate a complete Gleam source file from a list of scanned routes.
pub fn generate(routes: List(ScannedRoute)) -> String {
  let sorted = sort_routes(routes)
  let header = file_header(routes)
  let route_type = generate_route_type(sorted)
  let parse_fn = generate_parse_route(sorted)
  let path_fn = generate_route_to_path(sorted)
  let href_fn = generate_href()
  string.join([header, route_type, parse_fn, path_fn, href_fn], "\n\n") <> "\n"
}

// ---------------------------------------------------------------------------
// Sorting
// ---------------------------------------------------------------------------

/// Sort routes so that static patterns come before dynamic patterns at each
/// level of nesting. Within static groups, sort alphabetically.
fn sort_routes(routes: List(ScannedRoute)) -> List(ScannedRoute) {
  list.sort(routes, fn(a, b) { compare_routes(a.segments, b.segments) })
}

fn compare_routes(a: List(UrlSegment), b: List(UrlSegment)) -> order.Order {
  case a, b {
    [], [] -> order.Eq
    [], _ -> order.Lt
    _, [] -> order.Gt
    [ah, ..at], [bh, ..bt] ->
      case compare_segments(ah, bh) {
        order.Eq -> compare_routes(at, bt)
        other -> other
      }
  }
}

fn compare_segments(a: UrlSegment, b: UrlSegment) -> order.Order {
  case a, b {
    StaticSegment(_), DynamicSegment(_, _) -> order.Lt
    DynamicSegment(_, _), StaticSegment(_) -> order.Gt
    StaticSegment(an), StaticSegment(bn) -> string.compare(an, bn)
    DynamicSegment(an, _), DynamicSegment(bn, _) -> string.compare(an, bn)
  }
}

// ---------------------------------------------------------------------------
// File header
// ---------------------------------------------------------------------------

fn file_header(routes: List(ScannedRoute)) -> String {
  let int_import = case has_int_params(routes) {
    True -> "import gleam/int\n"
    False -> ""
  }
  let result_import = case has_string_params(routes) {
    True -> "import gleam/result\n"
    False -> ""
  }
  let uri_import = "import gleam/uri.{type Uri}\n"
  "// Generated by Rally — do not edit.\n\n"
  <> int_import
  <> result_import
  <> uri_import
  <> "import lustre/attribute.{type Attribute}"
}

fn has_int_params(routes: List(ScannedRoute)) -> Bool {
  list.any(routes, fn(r) { list.any(r.params, fn(p) { p.1 == IntParam }) })
}

fn has_string_params(routes: List(ScannedRoute)) -> Bool {
  list.any(routes, fn(r) { list.any(r.params, fn(p) { p.1 == StringParam }) })
}

// ---------------------------------------------------------------------------
// Route type
// ---------------------------------------------------------------------------

fn generate_route_type(routes: List(ScannedRoute)) -> String {
  let variants =
    routes
    |> list.map(route_variant_line)
    |> list.append(["  NotFound(uri: Uri)"])
    |> string.join("\n")
  "pub type Route {\n" <> variants <> "\n}"
}

fn route_variant_line(route: ScannedRoute) -> String {
  case route.params {
    [] -> "  " <> route.variant_name
    params -> {
      let fields =
        list.map(params, fn(p) {
          let #(name, param_type) = p
          name <> ": " <> param_type_to_gleam(param_type)
        })
        |> string.join(", ")
      "  " <> route.variant_name <> "(" <> fields <> ")"
    }
  }
}

fn param_type_to_gleam(param_type: types.ParamType) -> String {
  case param_type {
    IntParam -> "Int"
    StringParam -> "String"
  }
}

// ---------------------------------------------------------------------------
// parse_route
// ---------------------------------------------------------------------------

fn generate_parse_route(routes: List(ScannedRoute)) -> String {
  let arms =
    routes
    |> list.map(parse_route_arm)
    |> string.join("\n")
  "pub fn parse_route(uri: Uri) -> Route {\n  case uri.path_segments(uri.path) {\n"
  <> arms
  <> "\n    _ -> NotFound(uri:)\n  }\n}"
}

fn parse_route_arm(route: ScannedRoute) -> String {
  let ScannedRoute(
    segments:,
    variant_name:,
    params:,
    module_path: _,
    layout_module: _,
  ) = route
  let pattern = build_pattern(segments)
  let int_params =
    list.filter(params, fn(p) {
      let #(_, pt) = p
      pt == IntParam
    })
  case int_params {
    [] -> {
      let string_params =
        list.filter(params, fn(p) {
          let #(_, pt) = p
          pt == StringParam
        })
      let constructor = case string_params {
        [] -> build_constructor(variant_name, params)
        _ -> build_constructor_with_vals(variant_name:, params:, val_pairs: [])
      }
      "    " <> pattern <> " -> " <> constructor
    }
    [single] -> {
      let #(name, _) = single
      let val_name = name <> "_val"
      let constructor =
        build_constructor_with_vals(
          variant_name: variant_name,
          params: params,
          val_pairs: [#(name, val_name)],
        )
      "    "
      <> pattern
      <> " ->\n      case int.parse("
      <> name
      <> ") {\n        Ok("
      <> val_name
      <> ") -> "
      <> constructor
      <> "\n        Error(_) -> NotFound(uri:)\n      }"
    }
    multiple -> {
      let parse_exprs =
        list.map(multiple, fn(p) {
          let #(name, _) = p
          "int.parse(" <> name <> ")"
        })
        |> string.join(", ")
      let ok_patterns =
        list.map(multiple, fn(p) {
          let #(name, _) = p
          "Ok(" <> name <> "_val)"
        })
        |> string.join(", ")
      let val_pairs =
        list.map(multiple, fn(p) {
          let #(name, _) = p
          #(name, name <> "_val")
        })
      let constructor =
        build_constructor_with_vals(
          variant_name: variant_name,
          params: params,
          val_pairs: val_pairs,
        )
      "    "
      <> pattern
      <> " ->\n      case "
      <> parse_exprs
      <> " {\n        "
      <> ok_patterns
      <> " -> "
      <> constructor
      <> "\n        "
      <> string.join(list.map(multiple, fn(_) { "_" }), ", ")
      <> " -> NotFound(uri:)\n      }"
    }
  }
}

/// Build the list pattern for a route's segments, prefixed with [_lang, "admin"].
fn build_pattern(segments: List(UrlSegment)) -> String {
  let seg_parts =
    list.map(segments, fn(seg) {
      case seg {
        StaticSegment(name) -> "\"" <> name <> "\""
        DynamicSegment(param_name, _) -> param_name
      }
    })
  let all_parts = seg_parts
  "[" <> string.join(all_parts, ", ") <> "]"
}

/// Build the constructor expression using param names directly (shorthand label syntax).
fn build_constructor(
  variant_name: String,
  params: List(#(String, types.ParamType)),
) -> String {
  case params {
    [] -> variant_name
    _ -> {
      let fields =
        list.map(params, fn(p) {
          let #(name, _) = p
          name <> ":"
        })
        |> string.join(", ")
      variant_name <> "(" <> fields <> ")"
    }
  }
}

/// Build the constructor expression substituting int params with their _val names.
fn build_constructor_with_vals(
  variant_name variant_name: String,
  params params: List(#(String, types.ParamType)),
  val_pairs val_pairs: List(#(String, String)),
) -> String {
  case params {
    [] -> variant_name
    _ -> {
      let fields =
        list.map(params, fn(p) {
          let #(name, param_type) = p
          case param_type {
            StringParam ->
              name
              <> ": result.unwrap(uri.percent_decode("
              <> name
              <> "), "
              <> name
              <> ")"
            IntParam -> {
              let val_name = case
                list.find(val_pairs, fn(vp) { vp.0 == name })
              {
                Ok(#(_, v)) -> v
                Error(Nil) -> name
              }
              name <> ": " <> val_name
            }
          }
        })
        |> string.join(", ")
      variant_name <> "(" <> fields <> ")"
    }
  }
}

// ---------------------------------------------------------------------------
// route_to_path
// ---------------------------------------------------------------------------

fn generate_route_to_path(routes: List(ScannedRoute)) -> String {
  let arms =
    routes
    |> list.map(route_to_path_arm)
    |> string.join("\n")
  "pub fn route_to_path(route route: Route) -> String {\n  case route {\n"
  <> arms
  <> "\n    NotFound(uri:) -> uri.to_string(uri)\n  }\n}"
}

fn route_to_path_arm(route: ScannedRoute) -> String {
  let ScannedRoute(
    segments:,
    variant_name:,
    params:,
    module_path: _,
    layout_module: _,
  ) = route
  let destructor = build_constructor(variant_name, params)
  let path_expr = build_path_expr(segments)
  "    " <> destructor <> " -> " <> path_expr
}

fn build_path_expr(segments: List(UrlSegment)) -> String {
  case segments {
    [] -> "\"/\""
    _ ->
      string.join(
        merge_static_segments(segments: segments, buf: "", acc: []),
        " <> ",
      )
  }
}

fn merge_static_segments(
  segments segments: List(UrlSegment),
  buf buf: String,
  acc acc: List(String),
) -> List(String) {
  case segments {
    [] ->
      case buf {
        "" -> list.reverse(acc)
        _ -> list.reverse(["\"" <> buf <> "\"", ..acc])
      }
    [StaticSegment(name), ..rest] ->
      merge_static_segments(segments: rest, buf: buf <> "/" <> name, acc: acc)
    [DynamicSegment(param_name, IntParam), ..rest] -> {
      let acc = case buf {
        "" -> ["\"/\"", ..acc]
        _ -> ["\"" <> buf <> "/\"", ..acc]
      }
      merge_static_segments(segments: rest, buf: "", acc: [
        "int.to_string(" <> param_name <> ")",
        ..acc
      ])
    }
    [DynamicSegment(param_name, _), ..rest] -> {
      let acc = case buf {
        "" -> ["\"/\"", ..acc]
        _ -> ["\"" <> buf <> "/\"", ..acc]
      }
      merge_static_segments(segments: rest, buf: "", acc: [
        "uri.percent_encode(" <> param_name <> ")",
        ..acc
      ])
    }
  }
}

// ---------------------------------------------------------------------------
// href
// ---------------------------------------------------------------------------

fn generate_href() -> String {
  "pub fn href(route route: Route) -> Attribute(msg) {\n  attribute.href(route_to_path(route: route))\n}"
}

// ===========================================================================
// Dispatch generator
// ===========================================================================

/// Generate a complete page_dispatch.gleam source file from scanned routes.
pub fn generate_dispatch(
  routes routes: List(ScannedRoute),
  contracts contracts: List(#(ScannedRoute, PageContract)),
  has_client_context has_client_context: Bool,
  router_module router_module: String,
  client_context_module client_context_module: String,
) -> String {
  let contract_map =
    contracts
    |> list.map(fn(pair) { #({ pair.0 }.variant_name, pair.1) })
    |> dict.from_list
  let page_imports = dispatch_page_imports(routes, contract_map)
  let ctx_import = case has_client_context {
    True -> "\n" <> import_as(client_context_module, "client_context")
    False -> ""
  }
  let option_import = case has_client_context {
    True -> "import gleam/option.{type Option, None}\n"
    False -> ""
  }

  "// Generated by Rally — do not edit.\n\n"
  <> import_as(router_module, "router")
  <> "\n"
  <> option_import
  <> "import lustre/effect.{type Effect}
import lustre/element.{type Element}
import lustre/element/html
"
  <> page_imports
  <> ctx_import
  <> "\n\n"
  <> dispatch_page_model_type(routes, contract_map)
  <> "\n\n"
  <> dispatch_page_msg_type(routes, contract_map)
  <> "\n\n"
  <> dispatch_init_page(routes:, contract_map:, has_client_context:)
  <> "\n\n"
  <> dispatch_update_page(routes:, contract_map:, has_client_context:)
  <> "\n\n"
  <> dispatch_view_page(routes:, contract_map:, has_client_context:)
}

fn import_as(module_path: String, alias: String) -> String {
  case last_segment(module_path) == alias {
    True -> "import " <> module_path
    False -> "import " <> module_path <> " as " <> alias
  }
}

fn last_segment(module_path: String) -> String {
  case string.split(module_path, "/") |> list.last {
    Ok(seg) -> seg
    Error(Nil) -> module_path
  }
}

fn dispatch_page_model_type(
  routes: List(ScannedRoute),
  contract_map: dict.Dict(String, PageContract),
) -> String {
  let variants =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          Ok("  " <> route.variant_name <> "PageModel(" <> alias <> ".Model)")
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")
  "pub type PageModel {\n" <> variants <> "\n  NoPageModel\n}"
}

fn dispatch_page_msg_type(
  routes: List(ScannedRoute),
  contract_map: dict.Dict(String, PageContract),
) -> String {
  let variants =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          Ok("  " <> route.variant_name <> "PageMsg(" <> alias <> ".Msg)")
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")
  "pub type PageMsg {\n" <> variants <> "\n  NoPageMsg\n}"
}

fn dispatch_init_page(
  routes routes: List(ScannedRoute),
  contract_map contract_map: dict.Dict(String, PageContract),
  has_client_context has_client_context: Bool,
) -> String {
  let arms =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model && contract.has_init -> {
          let alias = page_module_alias(route)
          let param_args = dispatch_route_param_args(route)
          let call_args = case has_client_context, param_args {
            True, _ -> "(client_context" <> param_args <> ")"
            False, "" -> "()"
            False, _ -> "(" <> string.drop_start(param_args, 2) <> ")"
          }
          let wrap_model =
            route.variant_name
            <> "PageModel(model), effect.map(effects, "
            <> route.variant_name
            <> "PageMsg))"
          let init_body = case contract.has_fallible_init {
            False ->
              "      let #(model, effects) = "
              <> alias
              <> ".init"
              <> call_args
              <> "\n"
              <> "      #("
              <> wrap_model
            True ->
              "      case "
              <> alias
              <> ".init"
              <> call_args
              <> " {\n"
              <> "        Ok(#(model, effects)) -> #("
              <> wrap_model
              <> "\n"
              <> "        Error(Nil) -> #(NoPageModel, effect.none())\n"
              <> "      }"
          }
          Ok(
            "    "
            <> dispatch_route_pattern(route)
            <> " -> {\n"
            <> init_body
            <> "\n"
            <> "    }",
          )
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")

  let signature = case has_client_context {
    True ->
      "pub fn init_page(route route: router.Route, client_context client_context: client_context.ClientContext) -> #(PageModel, Effect(PageMsg)) {"
    False ->
      "pub fn init_page(route: router.Route) -> #(PageModel, Effect(PageMsg)) {"
  }

  signature
  <> "\n  case route {\n"
  <> arms
  <> "\n    _ -> #(NoPageModel, effect.none())\n  }\n}"
}

fn dispatch_update_page(
  routes routes: List(ScannedRoute),
  contract_map contract_map: dict.Dict(String, PageContract),
  has_client_context has_client_context: Bool,
) -> String {
  let arms =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          let vn = route.variant_name
          case has_client_context, contract.updates_client_context {
            True, True ->
              Ok(
                "    "
                <> vn
                <> "PageModel(model), "
                <> vn
                <> "PageMsg(msg) -> {\n"
                <> "      let #(new_model, effects, context_msg) = "
                <> alias
                <> ".update(client_context, model, msg)\n"
                <> "      #("
                <> vn
                <> "PageModel(new_model), effect.map(effects, "
                <> vn
                <> "PageMsg), context_msg)\n"
                <> "    }",
              )
            True, False ->
              Ok(
                "    "
                <> vn
                <> "PageModel(model), "
                <> vn
                <> "PageMsg(msg) -> {\n"
                <> "      let #(new_model, effects) = "
                <> alias
                <> ".update(client_context, model, msg)\n"
                <> "      #("
                <> vn
                <> "PageModel(new_model), effect.map(effects, "
                <> vn
                <> "PageMsg), None)\n"
                <> "    }",
              )
            _, _ ->
              Ok(
                "    "
                <> vn
                <> "PageModel(model), "
                <> vn
                <> "PageMsg(msg) -> {\n"
                <> "      let #(new_model, effects) = "
                <> alias
                <> ".update(model, msg)\n"
                <> "      #("
                <> vn
                <> "PageModel(new_model), effect.map(effects, "
                <> vn
                <> "PageMsg))\n"
                <> "    }",
              )
          }
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")

  case has_client_context {
    True -> {
      "pub fn update_page(page_model page_model: PageModel, page_msg page_msg: PageMsg, client_context client_context: client_context.ClientContext) -> #(PageModel, Effect(PageMsg), Option(client_context.ClientContextMsg)) {\n"
      <> "  case page_model, page_msg {\n"
      <> arms
      <> "\n    _, _ -> #(page_model, effect.none(), None)\n  }\n}"
    }
    False -> {
      "pub fn update_page(page_model page_model: PageModel, page_msg page_msg: PageMsg) -> #(PageModel, Effect(PageMsg)) {\n"
      <> "  case page_model, page_msg {\n"
      <> arms
      <> "\n    _, _ -> #(page_model, effect.none())\n  }\n}"
    }
  }
}

fn dispatch_view_page(
  routes routes: List(ScannedRoute),
  contract_map contract_map: dict.Dict(String, PageContract),
  has_client_context has_client_context: Bool,
) -> String {
  let arms =
    routes
    |> list.filter_map(fn(route) {
      case dict.get(contract_map, route.variant_name) {
        Ok(contract) if contract.has_model -> {
          let alias = page_module_alias(route)
          let view_args = case has_client_context {
            True -> "(client_context, model)"
            False -> "(model)"
          }
          Ok(
            "    "
            <> route.variant_name
            <> "PageModel(model) ->\n"
            <> "      element.map("
            <> alias
            <> ".view"
            <> view_args
            <> ", "
            <> route.variant_name
            <> "PageMsg)",
          )
        }
        _ -> Error(Nil)
      }
    })
    |> string.join("\n")

  let signature = case has_client_context {
    True ->
      "pub fn view_page(page_model page_model: PageModel, client_context client_context: client_context.ClientContext) -> Element(PageMsg) {"
    False -> "pub fn view_page(page_model: PageModel) -> Element(PageMsg) {"
  }

  signature
  <> "\n  case page_model {\n"
  <> arms
  <> "\n    NoPageModel -> html.div([], [html.text(\"Page not found\")])\n  }\n}"
}

fn dispatch_route_pattern(route: ScannedRoute) -> String {
  case route.params {
    [] -> "router." <> route.variant_name
    params ->
      "router."
      <> route.variant_name
      <> "("
      <> string.join(list.map(params, fn(p) { p.0 }), ", ")
      <> ")"
  }
}

fn dispatch_route_param_args(route: ScannedRoute) -> String {
  route.params
  |> list.map(fn(p) { ", " <> p.0 })
  |> string.join("")
}

fn page_module_alias(route: ScannedRoute) -> String {
  string.replace(route.module_path, "/", "_")
}

fn dispatch_page_imports(
  routes: List(ScannedRoute),
  contract_map: dict.Dict(String, PageContract),
) -> String {
  routes
  |> list.filter_map(fn(route) {
    case dict.get(contract_map, route.variant_name) {
      Ok(contract) if contract.has_model ->
        Ok("import " <> route.module_path <> " as " <> page_module_alias(route))
      _ -> Error(Nil)
    }
  })
  |> list.unique
  |> list.sort(string.compare)
  |> string.join("\n")
}

pub fn generate_empty_rpc_dispatch(
  atoms_module atoms_module: String,
  extra_params extra_params: List(rpc_dispatch.ExtraParam),
) -> String {
  rpc_dispatch.generate_with_extra_params(
    endpoints: [],
    atoms_module: Some(atoms_module),
    wire_module: None,
    extra_params:,
  )
}

pub fn normalize_rpc_dispatch_context_import(source: String) -> String {
  string.replace(
    source,
    "import server/server_context.{type ServerContext}",
    "import server_context.{type ServerContext}",
  )
}

pub fn normalize_rpc_dispatch_unused_fields(source: String) -> String {
  source
  |> string.split("\n")
  |> list.map(underscore_unused_dispatch_fields)
  |> string.join("\n")
}

fn underscore_unused_dispatch_fields(line: String) -> String {
  case string.split_once(line, " -> {") {
    Ok(#(before_arrow, after_arrow)) -> {
      case string.split_once(before_arrow, "(") {
        Ok(#(before_open, after_open)) -> {
          case string.split_once(after_open, ")") {
            Ok(#(fields, "")) -> {
              case string.contains(fields, ":") {
                True -> {
                  let underscored_fields =
                    fields
                    |> string.split(",")
                    |> list.map(underscore_field_shorthand)
                    |> string.join(",")
                  before_open
                  <> "("
                  <> underscored_fields
                  <> ") -> {"
                  <> after_arrow
                }
                False -> line
              }
            }
            _ -> line
          }
        }
        _ -> line
      }
    }
    _ -> line
  }
}

fn underscore_field_shorthand(field: String) -> String {
  let trimmed = string.trim(field)
  case string.ends_with(trimmed, ":") {
    True -> field <> " _"
    False -> field
  }
}

// ===========================================================================
// Protocol wire facade generator
// ===========================================================================

/// Generate the server-side protocol wire facade based on the protocol string.
pub fn generate_protocol_wire(
  protocol: String,
  atoms_module: String,
  contract_hash: String,
  rpc_dispatch_module: String,
  endpoints: List(HandlerEndpoint),
  auth_config: Option(AuthConfig),
  wire_import_module: String,
) -> String {
  case protocol {
    "json" ->
      json_protocol_wire_source(
        contract_hash,
        rpc_dispatch_module,
        endpoints,
        auth_config,
        wire_import_module,
      )
    _ ->
      etf_protocol_wire_source(atoms_module, rpc_dispatch_module, auth_config)
  }
}

/// Generate the client-side JS protocol facade module.
/// Re-exports FFI functions from the correct libero wire module
/// based on protocol (ETF re-exports from rpc_ffi.mjs, JSON wraps
/// encode_request with the contract hash).
pub fn generate_protocol_wire_js(
  protocol: String,
  contract_hash: String,
) -> String {
  case protocol {
    "json" ->
      "// Generated by Rally — do not edit.\n"
      <> "import { encode_request as libero_encode_request, decode_server_frame as libero_decode_server_frame, encode_flags, decode_flags_typed, identity } from \"../../libero/libero/json/wire_ffi.mjs\";\n"
      <> "import { Response, Push, Error as FrameError } from \"../../libero/libero/frame.mjs\";\n"
      <> "import { Ok, Error as ResultError, Empty, NonEmpty, BitArray } from \"../../gleam_stdlib/gleam.mjs\";\n"
      <> "import { Some, None } from \"../../gleam_stdlib/gleam/option.mjs\";\n"
      <> "import { typeRegistry } from \"./type_registry.mjs\";\n"
      <> "\n"
      <> "const contract_hash = \""
      <> contract_hash
      <> "\";\n"
      <> "\n"
      <> "// ---------- Libero typed JSON -> Gleam JS value ----------\n"
      <> "//\n"
      <> "// Response and push values arrive as Libero typed-value objects:\n"
      <> "//   { type: \"<module>.<Type>\", variant: \"<Variant>\", fields: ... }\n"
      <> "//\n"
      <> "// Container types (Result, Option) use array fields:\n"
      <> "//   Result Ok:    { ..., fields: [inner_value] }\n"
      <> "//   Result Error: { ..., fields: [inner_value] }\n"
      <> "//   Option Some:  { ..., fields: [inner_value] }\n"
      <> "//   Option None:  { ..., fields: {} }\n"
      <> "//   User types:   { ..., fields: { label: value, ... } }\n"
      <> "\n"
      <> "function typedJsonToGleamValue(value) {\n"
      <> "  if (value === undefined || value === null) return undefined;\n"
      <> "  if (typeof value !== \"object\") return value;\n"
      <> "  if (Array.isArray(value)) return value.map(v => typedJsonToGleamValue(v));\n"
      <> "  // Libero typed-value shape: { type, variant, fields }\n"
      <> "  if (value.type && value.variant && value.fields !== undefined) {\n"
      <> "    const t = value.type;\n"
      <> "    const v = value.variant;\n"
      <> "    const f = value.fields;\n"
      <> "    if (t === \"gleam.Nil\") return undefined;\n"
      <> "    if (t === \"gleam.String\") return f.value;\n"
      <> "    if (t === \"gleam.Int\") return f.value;\n"
      <> "    if (t === \"gleam.Float\") return f.value;\n"
      <> "    if (t === \"gleam.Bool\") return f.value;\n"
      <> "    if (t === \"gleam.Result\" || t === \"gleam/result.Result\") {\n"
      <> "      const inner = typedJsonToGleamValue(Array.isArray(f) ? f[0] : f.value);\n"
      <> "      return v === \"Ok\" ? new Ok(inner) : new ResultError(inner);\n"
      <> "    }\n"
      <> "    if (t === \"gleam.Option\" || t === \"gleam/option.Option\") {\n"
      <> "      if (v === \"None\" || (Array.isArray(f) && f.length === 0) || Object.keys(f).length === 0) return new None();\n"
      <> "      const inner = typedJsonToGleamValue(Array.isArray(f) ? f[0] : f.value);\n"
      <> "      return new Some(inner);\n"
      <> "    }\n"
      <> "    if (t === \"gleam.List\") {\n"
      <> "      if (v === \"Empty\") return new Empty();\n"
      <> "      const items = (f.items || f).map(item => typedJsonToGleamValue(item));\n"
      <> "      let list = new Empty();\n"
      <> "      for (let i = items.length - 1; i >= 0; i--) list = new NonEmpty(items[i], list);\n"
      <> "      return list;\n"
      <> "    }\n"
      <> "    if (t === \"gleam.Tuple\") {\n"
      <> "      return (f.elements || f).map(e => typedJsonToGleamValue(e));\n"
      <> "    }\n"
      <> "    // User types: dispatch by full type identity\n"
      <> "    // Key by full \"type\" + \"#\" + \"variant\" so a mismatched parent type\n"
      <> "    // (\"some/module.OldType\" with variant \"Discount\") never resolves to\n"
      <> "    // the registry entry for \"some/module.Discount\".\n"
      <> "    const key = t + \"#\" + v;\n"
      <> "    const ctor = typeRegistry[key];\n"
      <> "    if (!ctor) {\n"
      <> "      throw new Error(\"Unknown type in JSON decode: type=\" + t + \" variant=\" + v + \" (lookup key: \" + key + \")\");\n"
      <> "    }\n"
      <> "    if (Array.isArray(f)) {\n"
      <> "      return ctor(f.map(val => typedJsonToGleamValue(val)));\n"
      <> "    }\n"
      <> "    const fields = {};\n"
      <> "    for (const [fieldKey, val] of Object.entries(f)) {\n"
      <> "      fields[fieldKey] = typedJsonToGleamValue(val);\n"
      <> "    }\n"
      <> "    return ctor(fields);\n"
      <> "  }\n"
      <> "  return value;\n"
      <> "}\n"
      <> "\n"
      <> "// ---------- Public API ----------\n"
      <> "//\n"
      <> "// encode_request receives messages pre-encoded by Gleam typed JSON\n"
      <> "// codecs (types.json_encode_client_msg). The value is already in\n"
      <> "// the Libero typed-value shape — pass through without conversion.\n"
      <> "\n"
      <> "export function encode_request(module, requestId, msg) {\n"
      <> "  return libero_encode_request(module, requestId, msg, contract_hash);\n"
      <> "}\n"
      <> "\n"
      <> "export function decode_server_frame(data) {\n"
      <> "  try {\n"
      <> "    const result = libero_decode_server_frame(data);\n"
      <> "    if (result instanceof ResultError) return result;\n"
      <> "    const frame = result[0];\n"
      <> "    if (frame instanceof Response) {\n"
      <> "      try {\n"
      <> "        return new Ok({ kind: \"response\", requestId: frame.request_id, value: typedJsonToGleamValue(frame.value) });\n"
      <> "      } catch (e) {\n"
      <> "        return new Ok({ kind: \"error\", requestId: frame.request_id, errors: [[\"decode\", e.message || \"JSON decode error\"]] });\n"
      <> "      }\n"
      <> "    }\n"
      <> "    if (frame instanceof Push) {\n"
      <> "      try {\n"
      <> "        return new Ok({ kind: \"push\", module: frame.module, value: typedJsonToGleamValue(frame.value) });\n"
      <> "      } catch (e) {\n"
      <> "        return new ResultError(e.message || \"JSON decode error\");\n"
      <> "      }\n"
      <> "    }\n"
      <> "    if (frame instanceof FrameError) {\n"
      <> "      const rid = frame.request_id;\n"
      <> "      return new Ok({ kind: \"error\", requestId: rid instanceof Some ? rid[0] : null, errors: frame.errors });\n"
      <> "    }\n"
      <> "    return result;\n"
      <> "  } catch (e) {\n"
      <> "    return new ResultError(e.message || \"JSON decode error\");\n"
      <> "  }\n"
      <> "}\n"
      <> "\n"
      <> "export { encode_flags, decode_flags_typed, identity, typedJsonToGleamValue };\n"
    _ ->
      "// Generated by Rally — do not edit.
export { encode_request, decode_server_frame, identity } from \"../../libero/libero/rpc_ffi.mjs\";
export { encode_flags, decode_flags_typed } from \"../../libero/libero/wire.mjs\";
"
  }
}

fn etf_protocol_wire_source(
  atoms_module: String,
  rpc_dispatch_module: String,
  auth_config: Option(AuthConfig),
) -> String {
  let has_auth = option.is_some(auth_config)
  let auth_import = case auth_config {
    Some(AuthConfig(auth_module:)) -> import_as(auth_module, "auth") <> "\n"
    None -> ""
  }
  let dispatch_fn = case has_auth {
    True ->
      "pub fn dispatch_rpc(
  envelope envelope: RpcEnvelope,
  server_context server_context: ServerContext,
  identity identity: auth.Identity,
) -> #(RpcResult, ServerContext) {
  ensure_atoms()
  let #(data, server_context) =
    rpc_dispatch.handle(server_context:, data: envelope.raw, identity:)
  #(RpcResult(data:), server_context)
}
"
    False ->
      "pub fn dispatch_rpc(
  envelope envelope: RpcEnvelope,
  server_context server_context: ServerContext,
) -> #(RpcResult, ServerContext) {
  ensure_atoms()
  let #(data, server_context) =
    rpc_dispatch.handle(server_context:, data: envelope.raw)
  #(RpcResult(data:), server_context)
}
"
  }

  "// Generated by Rally — do not edit.

import gleam/bytes_tree
import gleam/dynamic.{type Dynamic}
import libero/error.{type DecodeError}
import libero/wire as libero_wire
import mist.{type WebsocketConnection, type WebsocketMessage}
import server_context.{type ServerContext}
import " <> rpc_dispatch_module <> " as rpc_dispatch
" <> auth_import <> "

@external(erlang, \"" <> atoms_module <> "\", \"ensure\")
fn ensure_atoms() -> Nil

pub fn page_init_ok() -> Nil { Nil }

pub fn encode(value: a) -> BitArray { libero_wire.encode(value) }
pub fn decode_request(data: BitArray) -> Result(#(String, Int, Dynamic), DecodeError) { libero_wire.decode_request(data) }
pub fn encode_request(module module: String, request_id request_id: Int, msg msg: a) -> BitArray { libero_wire.encode_request(module:, request_id:, msg:) }
pub fn encode_response(request_id request_id: Int, value value: a) -> BitArray { libero_wire.encode_response(request_id:, value:) }
pub fn tag_response(request_id request_id: Int, data data: BitArray) -> BitArray { libero_wire.tag_response(request_id:, data:) }
pub fn encode_push(module module: String, value value: a) -> BitArray { libero_wire.encode_push(module:, value:) }
pub fn variant_tag(value: Dynamic) -> Result(String, Nil) { libero_wire.variant_tag(value) }
pub fn coerce(value: a) -> b { libero_wire.coerce(value) }

pub fn encode_flags(value: a) -> String { libero_wire.encode_flags(value) }
pub fn decode_flags_typed(flags: String, decoder_name: String) -> Result(a, DecodeError) { libero_wire.decode_flags_typed(flags:, decoder_name:) }

pub opaque type RpcEnvelope {
  RpcEnvelope(request_id: Int, identity: String, raw: BitArray)
}

pub opaque type RpcResult {
  RpcResult(data: BitArray)
}

pub fn rpc_request_id(envelope: RpcEnvelope) -> Int { envelope.request_id }
pub fn rpc_identity(envelope: RpcEnvelope) -> String { envelope.identity }
pub fn rpc_raw_payload(envelope: RpcEnvelope) -> BitArray { envelope.raw }

pub fn decode_rpc_envelope(data: BitArray) -> Result(RpcEnvelope, Nil) {
  case libero_wire.decode_request(data) {
    Ok(#(\"rpc\", request_id, raw)) ->
      case libero_wire.variant_tag(raw) {
        Ok(tag) -> Ok(RpcEnvelope(request_id:, identity: tag, raw: data))
        Error(Nil) -> Error(Nil)
      }
    Ok(#(_, _, _)) -> Error(Nil)
    Error(_) -> Error(Nil)
  }
}

pub fn decode_ws_rpc_envelope(msg: WebsocketMessage(a)) -> Result(RpcEnvelope, Nil) {
  case msg {
    mist.Binary(data) ->
      case decode_rpc_envelope(data) {
        Ok(envelope) if envelope.request_id == 0 -> Error(Nil)
        result -> result
      }
    _ -> Error(Nil)
  }
}

" <> dispatch_fn <> "
pub fn send_rpc_result(conn: WebsocketConnection, result: RpcResult) -> Nil {
  let _send_result = mist.send_binary_frame(conn, result.data)
  Nil
}

pub fn rpc_result_body(result: RpcResult) -> bytes_tree.BytesTree {
  bytes_tree.from_bit_array(result.data)
}

pub fn rpc_content_type() -> String {
  \"application/octet-stream\"
}

pub fn auth_error_result(request_id: Int, message: String) -> RpcResult {
  RpcResult(data: encode_response(request_id:, value: Error(message)))
}

pub fn error_result(request_id: Int, message: String) -> RpcResult {
  RpcResult(data: encode_response(request_id:, value: Error(message)))
}

pub fn malformed_rpc_result() -> RpcResult {
  RpcResult(data: encode_response(request_id: 0, value: Error(\"Bad request\")))
}

@external(erlang, \"rally_runtime_wire_ffi\", \"tuple_element\")
pub fn tuple_element(_tuple: Dynamic, _index: Int) -> Dynamic { dynamic.nil() }
"
}

fn json_protocol_wire_source(
  contract_hash: String,
  _rpc_dispatch_module: String,
  endpoints: List(HandlerEndpoint),
  auth_config: Option(AuthConfig),
  wire_import_module: String,
) -> String {
  let has_auth = option.is_some(auth_config)
  let auth_import = case auth_config {
    Some(AuthConfig(auth_module:)) -> import_as(auth_module, "auth") <> "\n"
    None -> ""
  }
  let json_codecs_module =
    string.replace(wire_import_module, "protocol_wire", "json_codecs")
  let handler_imports = case json_rpc_dispatch.handler_imports(endpoints) {
    [] -> ""
    imports -> string.join(imports, "\n") <> "\n"
  }
  let json_dispatch =
    json_rpc_dispatch.generate_json_dispatch_function_with_prefix(
      endpoints,
      has_auth,
      "",
    )
  let dispatch_fn = case has_auth {
    True ->
      "pub fn dispatch_rpc(
  envelope envelope: RpcEnvelope,
  server_context server_context: ServerContext,
  identity identity: auth.Identity,
) -> #(RpcResult, ServerContext) {
  let #(frame, server_context) =
    json_dispatch(
      message: envelope.message,
      request_id: envelope.request_id,
      server_context:,
      identity:,
    )
  #(RpcResult(text: frame), server_context)
}
"
    False ->
      "pub fn dispatch_rpc(
  envelope envelope: RpcEnvelope,
  server_context server_context: ServerContext,
) -> #(RpcResult, ServerContext) {
  let #(frame, server_context) =
    json_dispatch(
      message: envelope.message,
      request_id: envelope.request_id,
      server_context:,
    )
  #(RpcResult(text: frame), server_context)
}
"
  }

  "// Generated by Rally — do not edit.

import gleam/bit_array
import gleam/bytes_tree
import gleam/dynamic.{type Dynamic}
import gleam/dynamic/decode
import gleam/io
import gleam/json
import gleam/option.{type Option, None, Some}
import libero/frame.{type ServerFrame}
import libero/json/error.{type JsonError, JsonError}
import libero/json/wire.{type RequestEnvelope} as json_wire
import libero/trace
import mist.{type WebsocketConnection, type WebsocketMessage}
import server_context.{type ServerContext}
import " <> json_codecs_module <> " as json_codecs
" <> handler_imports <> auth_import <> "

const contract_hash = \"" <> contract_hash <> "\"

pub fn page_init_ok() -> json.Json { json.null() }

pub fn encode_request(module module: String, request_id request_id: Int, msg msg: json.Json) -> String {
  json_wire.encode_request(module:, request_id:, msg:, contract_hash:)
}

pub fn decode_server_frame(data: String) -> Result(ServerFrame(Dynamic), List(JsonError)) {
  json_wire.decode_server_frame(data)
}

pub fn encode_response(request_id request_id: Int, value value: json.Json) -> String {
  json_wire.encode_response(request_id:, value:)
}

pub fn encode_error(request_id request_id: Option(Int), errors errors: List(JsonError)) -> String {
  json_wire.encode_error(request_id:, errors:)
}

pub fn encode_push(module module: String, value value: json.Json) -> String {
  json_wire.encode_push(module:, value:)
}

pub fn encode_flags(value: json.Json) -> String {
  json_wire.encode_flags(value)
}

pub fn decode_flags_typed(flags: String, decoder: fn(Dynamic) -> Result(a, List(JsonError))) -> Result(a, List(JsonError)) {
  json_wire.decode_flags_typed(flags, decoder)
}

pub fn decode_request(data: String) -> Result(RequestEnvelope, List(JsonError)) {
  json_wire.decode_request(data, contract_hash)
}

pub opaque type RpcEnvelope {
  RpcEnvelope(request_id: Int, identity: String, message: Dynamic, raw_text: String)
}

pub opaque type RpcResult {
  RpcResult(text: String)
}

pub fn rpc_request_id(envelope: RpcEnvelope) -> Int { envelope.request_id }
pub fn rpc_identity(envelope: RpcEnvelope) -> String { envelope.identity }
pub fn rpc_raw_payload(envelope: RpcEnvelope) -> BitArray { bit_array.from_string(envelope.raw_text) }

pub fn decode_rpc_envelope(data: BitArray) -> Result(RpcEnvelope, Nil) {
  case bit_array.to_string(data) {
    Error(_) -> Error(Nil)
    Ok(text) -> decode_rpc_envelope_text(text)
  }
}

pub fn decode_ws_rpc_envelope(msg: WebsocketMessage(a)) -> Result(RpcEnvelope, Nil) {
  case msg {
    mist.Text(data) ->
      case decode_rpc_envelope_text(data) {
        Ok(envelope) if envelope.request_id == 0 -> Error(Nil)
        result -> result
      }
    _ -> Error(Nil)
  }
}

fn decode_rpc_envelope_text(data: String) -> Result(RpcEnvelope, Nil) {
  case json_wire.decode_request(data, contract_hash) {
    Error(_) -> Error(Nil)
    Ok(envelope) ->
      case envelope.module == \"rpc\" {
        False -> Error(Nil)
        True -> {
          case extract_message_type(envelope.message) {
            Error(_) -> Error(Nil)
            Ok(type_str) ->
              Ok(RpcEnvelope(
                request_id: envelope.request_id,
                identity: type_str,
                message: envelope.message,
                raw_text: data,
              ))
          }
        }
      }
  }
}

fn extract_message_type(message: Dynamic) -> Result(String, Nil) {
  case decode.run(
    message,
    decode.field(\"type\", decode.string, fn(x) {
      decode.success(x)
    }),
  ) {
    Ok(type_str) -> Ok(type_str)
    Error(_) -> Error(Nil)
  }
}

" <> json_dispatch <> "\n" <> dispatch_fn <> "
pub fn send_rpc_result(conn: WebsocketConnection, result: RpcResult) -> Nil {
  let _send_result = mist.send_text_frame(conn, result.text)
  Nil
}

pub fn rpc_result_body(result: RpcResult) -> bytes_tree.BytesTree {
  bytes_tree.from_string(result.text)
}

pub fn rpc_content_type() -> String {
  \"application/json\"
}

pub fn auth_error_result(request_id: Int, message: String) -> RpcResult {
  let result: Result(Nil, String) = Error(message)
  let encoded =
    json_codecs.json_encode_gleam_result__result(
      result,
      fn(_x) { json.null() },
      fn(x) { json.string(x) },
    )
  RpcResult(text: encode_response(request_id:, value: encoded))
}

pub fn error_result(request_id: Int, message: String) -> RpcResult {
  RpcResult(text: json_wire.encode_error(
    request_id: Some(request_id),
    errors: [JsonError(\"rpc\", message)],
  ))
}

pub fn malformed_rpc_result() -> RpcResult {
  RpcResult(text: json_wire.encode_error(
    request_id: None,
    errors: [JsonError(\"frame\", \"invalid RPC frame\")],
  ))
}

pub fn variant_tag(_value: Dynamic) -> Result(String, Nil) {
  panic as \"JSON protocol: variant_tag not implemented\"
}

pub fn encode(_value: a) -> BitArray {
  panic as \"JSON protocol: encode not implemented\"
}
"
}
